// ========================================================
// CSE INDUSTRY PROJECT MASTER GUIDE - COMPLETE DATA BANK
// Real-World Problems • Industry Technologies • 60 Projects across 12 Fields
// ========================================================

export const PROJECT_DOMAINS = [
  {
    id: 'all',
    name: 'All Fields',
    icon: 'Sparkles',
    count: 60,
    color: '#3b82f6',
    description: 'Explore the complete bank of 60 real-world industry projects across all 12 computing disciplines.',
  },
  {
    id: 'ai-ml',
    name: 'AI / Machine Learning',
    icon: 'Brain',
    count: 5,
    color: '#8b5cf6',
    industryStack: 'Python, NumPy, pandas, scikit-learn, PyTorch/TensorFlow, FastAPI, PostgreSQL/MongoDB, Docker',
    description: 'Predictive modeling, computer vision, time-series forecasting, anomaly detection, and enterprise ML pipelines.',
  },
  {
    id: 'gen-ai',
    name: 'Generative AI / LLM Engineering',
    icon: 'Sparkles',
    count: 5,
    color: '#ec4899',
    industryStack: 'Python, FastAPI, LLM APIs, embeddings, vector DB, RAG, LangChain/LlamaIndex, React/Next.js',
    description: 'Retrieval Augmented Generation (RAG), autonomous multi-agent systems, semantic search, and document intelligence.',
  },
  {
    id: 'cybersecurity',
    name: 'Cybersecurity',
    icon: 'Shield',
    count: 5,
    color: '#10b981',
    industryStack: 'Python, Linux, Networking, SQL, OWASP, Docker, SIEM concepts, cryptography',
    description: 'Vulnerability scanners, SIEM log analysis, endpoint detection, threat intelligence, and cloud security posture.',
  },
  {
    id: 'frontend',
    name: 'Web Development / Frontend',
    icon: 'Layout',
    count: 5,
    color: '#06b6d4',
    industryStack: 'HTML, CSS, JavaScript, TypeScript, React/Next.js, testing, accessibility, WebSockets',
    description: 'Accessible client portals, state management dashboards, multi-vendor marketplaces, and real-time collaboration boards.',
  },
  {
    id: 'fullstack',
    name: 'Full-Stack Development',
    icon: 'Globe',
    count: 5,
    color: '#3b82f6',
    industryStack: 'React/Next.js, TypeScript/JavaScript, Node.js/Express/NestJS, PostgreSQL/MongoDB, Redis, Docker',
    description: 'Production CRUD platforms, multi-tenant SaaS architectures, healthcare scheduling, and fintech cashflow suites.',
  },
  {
    id: 'backend',
    name: 'Backend / API Engineering',
    icon: 'Server',
    count: 5,
    color: '#f59e0b',
    industryStack: 'Node.js, TypeScript, Java/Spring Boot, Python/FastAPI, PostgreSQL, Redis, Kafka/RabbitMQ',
    description: 'Event-driven microservices, high-throughput API gateways, idempotent order processing, and notification brokers.',
  },
  {
    id: 'data-science',
    name: 'Data Science / Analytics',
    icon: 'BarChart3',
    count: 5,
    color: '#14b8a6',
    industryStack: 'Python, pandas, SQL, statistics, Jupyter, Power BI/Tableau optional, ML, Airflow',
    description: 'Exploratory data analysis, automated ETL pipelines, demand forecasting models, and executive KPI intelligence.',
  },
  {
    id: 'devops',
    name: 'Cloud / DevOps / SRE',
    icon: 'Cloud',
    count: 5,
    color: '#f97316',
    industryStack: 'AWS/Azure/GCP, Linux, Docker, Kubernetes, GitHub Actions, Terraform, Prometheus/Grafana',
    description: 'Automated CI/CD pipelines, Kubernetes microservice clusters, observability monitoring, and internal developer platforms.',
  },
  {
    id: 'mobile',
    name: 'Mobile / Cross-Platform',
    icon: 'Smartphone',
    count: 5,
    color: '#6366f1',
    industryStack: 'Flutter/Dart or React Native/TypeScript, REST APIs, Firebase/PostgreSQL, notifications',
    description: 'Offline-first sync apps, campus lifestyle companions, real-time last-mile delivery tracking, and IoT fleet managers.',
  },
  {
    id: 'iot',
    name: 'IoT / Edge / Embedded',
    icon: 'Cpu',
    count: 5,
    color: '#84cc16',
    industryStack: 'C/C++, Python, ESP32/Arduino, MQTT, sensors, Node.js/Python, cloud, time-series DB',
    description: 'Smart energy meters, cold-chain temperature telemetry, industrial vibration monitors, and factory digital twins.',
  },
  {
    id: 'blockchain',
    name: 'Blockchain / Web3',
    icon: 'Lock',
    count: 5,
    color: '#a855f7',
    industryStack: 'Solidity, Ethereum-compatible networks, JavaScript/TypeScript, Node.js, React, wallet libraries',
    description: 'Academic certificate verification DApps, donation audit ledgers, supply chain provenance, and token-gated portals.',
  },
  {
    id: 'system-design',
    name: 'Software Engg / System Design',
    icon: 'Layers',
    count: 5,
    color: '#0284c7',
    industryStack: 'Java/TypeScript/Python/Go, UML, design patterns, testing, architecture, databases, queues',
    description: 'Scalable URL shorteners, online exam engines, concurrent ride-dispatch simulators, and distributed job workers.',
  },
];

export const INDUSTRY_PROJECTS = [
  // ==========================================
  // 1. AI / MACHINE LEARNING (5 PROJECTS)
  // ==========================================
  {
    id: 'ai-1',
    title: 'AI Resume Skill Analyzer',
    domainId: 'ai-ml',
    domainName: 'AI / Machine Learning',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Analyze a resume and job description; extract skills, identify gaps and generate a personalized learning checklist.',
    techStack: 'Python, NLP, spaCy/Transformers, FastAPI, React, PostgreSQL',
    demonstrate: 'Skill extraction, semantic cosine similarity, REST API integration',
    scope: 'MVP with clean UI, authentication where needed, database and comprehensive README.',
    industryStack: 'Python, spaCy, FastAPI, React, PostgreSQL',
    tags: ['NLP', 'Skill Matching', 'FastAPI', 'Career Tech'],
    featured: false,
  },
  {
    id: 'ai-2',
    title: 'Smart Customer Support Ticket Classifier',
    domainId: 'ai-ml',
    domainName: 'AI / Machine Learning',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Automatically classify support tickets by category/priority and route them to designated engineering and support teams.',
    techStack: 'Python, scikit-learn/PyTorch, FastAPI, React, PostgreSQL, Docker',
    demonstrate: 'Multi-class classification, confidence thresholds, human-in-the-loop review workflow',
    scope: 'Production-style API, role-based access, data validation, automated unit tests, containerized deployment and basic monitoring.',
    industryStack: 'Python, PyTorch, FastAPI, Docker, PostgreSQL',
    tags: ['Classification', 'Ticket Routing', 'Docker', 'MLOps'],
    featured: true,
  },
  {
    id: 'ai-3',
    title: 'Predictive Maintenance Dashboard',
    domainId: 'ai-ml',
    domainName: 'AI / Machine Learning',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Use machine and sensor history to predict equipment maintenance failure risk and trigger preventative alerts.',
    techStack: 'Python, pandas, ML (Random Forest/XGBoost), FastAPI, React, PostgreSQL, Docker',
    demonstrate: 'Time-series feature engineering, prediction REST API, automated anomaly alerts',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Python, pandas, XGBoost, FastAPI, React',
    tags: ['Time Series', 'Predictive Maintenance', 'IoT Analytics', 'Dashboard'],
    featured: false,
  },
  {
    id: 'ai-4',
    title: 'Fraud Detection & Risk Scoring Platform',
    domainId: 'ai-ml',
    domainName: 'AI / Machine Learning',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'TY / Final',
    problem: 'Score financial transactions in real-time for fraud risk and provide explainable investigation queues for compliance officers.',
    techStack: 'Python, XGBoost/PyTorch, FastAPI, Kafka optional, PostgreSQL, Redis, React',
    demonstrate: 'Imbalanced dataset learning (SMOTE), SHAP explainability, streaming architecture, sub-second inference',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Python, PyTorch, Kafka, Redis, PostgreSQL, SHAP',
    tags: ['FinTech', 'Fraud Detection', 'XGBoost', 'Kafka', 'SHAP'],
    featured: true,
  },
  {
    id: 'ai-5',
    title: 'Enterprise AI Decision Intelligence Platform',
    domainId: 'ai-ml',
    domainName: 'AI / Machine Learning',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Combine forecasting, anomaly detection, document intelligence and an AI analyst dashboard for executive business teams.',
    techStack: 'Python, PyTorch, LLM API/local model, FastAPI, PostgreSQL, vector DB (pgvector), Redis, Docker/K8s',
    demonstrate: 'RAG pipelines, multi-model forecasting, anomaly detection, evaluation harnesses, complete audit trail',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Python, PyTorch, Vector DB, Kubernetes, Redis',
    tags: ['Decision Intelligence', 'Enterprise AI', 'RAG', 'Kubernetes'],
    featured: true,
  },

  // ==========================================
  // 2. GENERATIVE AI / LLM ENGINEERING (5 PROJECTS)
  // ==========================================
  {
    id: 'gen-1',
    title: 'College Document Q&A Assistant',
    domainId: 'gen-ai',
    domainName: 'Generative AI / LLM Engineering',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Ask natural language questions over college rules, exam circulars, notices and PDF handbooks with verifiable cited answers.',
    techStack: 'Python, OpenAI/HuggingFace embeddings, ChromaDB/FAISS vector DB, FastAPI, React',
    demonstrate: 'RAG fundamentals, text chunking strategies, document ingestion pipelines',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'Python, ChromaDB, FastAPI, React, LangChain',
    tags: ['RAG', 'Vector Search', 'ChromaDB', 'Campus Tech'],
    featured: false,
  },
  {
    id: 'gen-2',
    title: 'Company Knowledge Copilot',
    domainId: 'gen-ai',
    domainName: 'Generative AI / LLM Engineering',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Search internal enterprise policies, technical documentation and departmental FAQs with strict role-based data access.',
    techStack: 'Python, LLM API, RAG, PostgreSQL/pgvector, React, Docker',
    demonstrate: 'Role-Based Access Control (RBAC) at embedding level, citation verification, retrieval evaluation (RAGAS)',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Python, pgvector, LangChain, React, Docker',
    tags: ['Copilot', 'Enterprise RAG', 'RBAC', 'PostgreSQL'],
    featured: true,
  },
  {
    id: 'gen-3',
    title: 'AI Meeting Action Manager',
    domainId: 'gen-ai',
    domainName: 'Generative AI / LLM Engineering',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Convert unstructured meeting transcripts and audio notes into executive summaries, key decisions, assignees and tracked deadlines.',
    techStack: 'Python, Whisper speech-to-text API, LLM, FastAPI, PostgreSQL, React',
    demonstrate: 'Structured JSON extraction (Pydantic), task workflow automation, prompt engineering',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Python, Whisper, FastAPI, PostgreSQL, React',
    tags: ['Speech to Text', 'Structured Output', 'Meeting Intelligence'],
    featured: false,
  },
  {
    id: 'gen-4',
    title: 'AI Customer Support Agent with Human Handoff',
    domainId: 'gen-ai',
    domainName: 'Generative AI / LLM Engineering',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'TY / Final',
    problem: 'Autonomously resolve common customer support requests, retrieve database facts, and seamlessly escalate uncertain cases to human agents.',
    techStack: 'Python, LLM, RAG, function/tool calling, Redis, PostgreSQL, WebSockets, React',
    demonstrate: 'Safety guardrails (NeMo), confidence estimation, tool use execution, live agent escalation queue',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Python, LangGraph, Redis, WebSockets, PostgreSQL',
    tags: ['Agentic AI', 'Tool Calling', 'Human Handoff', 'WebSockets'],
    featured: true,
  },
  {
    id: 'gen-5',
    title: 'Enterprise Multi-Agent Operations Assistant',
    domainId: 'gen-ai',
    domainName: 'Generative AI / LLM Engineering',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Specialized autonomous agents coordinate analytics, ticket resolution, documentation and workflow actions under strict permissions.',
    techStack: 'Python, LLM, AutoGen/LangGraph agent orchestration, FastAPI, RabbitMQ event queue, PostgreSQL, React',
    demonstrate: 'Multi-agent orchestration, state machines, permission boundaries, LangSmith observability, tamper-proof audit logs',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Python, LangGraph, RabbitMQ, PostgreSQL, Next.js',
    tags: ['Multi-Agent', 'AutoGen', 'LangGraph', 'Enterprise Automation'],
    featured: true,
  },

  // ==========================================
  // 3. CYBERSECURITY (5 PROJECTS)
  // ==========================================
  {
    id: 'sec-1',
    title: 'Password Security & Phishing Awareness Portal',
    domainId: 'cybersecurity',
    domainName: 'Cybersecurity',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Train campus/corporate users with safe educational email simulation scenarios and calculate password entropy scorecards.',
    techStack: 'React, Node.js/Express, PostgreSQL, Python entropy scripts',
    demonstrate: 'Authentication, cryptographic hashing (bcrypt/argon2), awareness analytics',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'React, Node.js, PostgreSQL, Argon2',
    tags: ['Phishing Simulation', 'Password Entropy', 'Awareness'],
    featured: false,
  },
  {
    id: 'sec-2',
    title: 'Web Vulnerability Scanner for Authorized Labs',
    domainId: 'cybersecurity',
    domainName: 'Cybersecurity',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Scan a controlled testbed target for common security misconfigurations, header weaknesses, and OWASP Top 10 vulnerabilities.',
    techStack: 'Python, requests/BeautifulSoup, FastAPI, React, Docker',
    demonstrate: 'OWASP Top 10 principles, safe automated scanning, structured security remediation reports',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Python, FastAPI, Docker, React',
    tags: ['OWASP Top 10', 'Vulnerability Scanner', 'Security Audit'],
    featured: true,
  },
  {
    id: 'sec-3',
    title: 'Security Log Analyzer / Mini SIEM',
    domainId: 'cybersecurity',
    domainName: 'Cybersecurity',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Collect and search Linux auth, firewall and web logs; detect brute-force patterns, SQLi attempts, and trigger SOC alerts.',
    techStack: 'Python, FastAPI, PostgreSQL/OpenSearch, Regex/Logstash, React',
    demonstrate: 'Log ingestion, parsing pipelines, Sigma-style detection rules, real-time alert dashboards',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Python, OpenSearch, FastAPI, React',
    tags: ['SIEM', 'Log Analysis', 'SOC', 'Incident Response'],
    featured: false,
  },
  {
    id: 'sec-4',
    title: 'Endpoint Threat Detection Dashboard',
    domainId: 'cybersecurity',
    domainName: 'Cybersecurity',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'TY / Final',
    problem: 'Analyze endpoint telemetry for suspicious process trees, unauthorized persistence mechanisms, and anomalous network behaviors.',
    techStack: 'Python, Linux osquery/eBPF telemetry, FastAPI, OpenSearch, React, Docker',
    demonstrate: 'High-throughput telemetry ingestion, behavioral detection rules, MITRE ATT&CK mapping, alert triage',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Python, eBPF, OpenSearch, Docker, MITRE ATT&CK',
    tags: ['EDR', 'MITRE ATT&CK', 'Endpoint Security', 'eBPF'],
    featured: true,
  },
  {
    id: 'sec-5',
    title: 'Cloud Security Posture Management Platform',
    domainId: 'cybersecurity',
    domainName: 'Cybersecurity',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Check authorized AWS/GCP cloud resources against CIS benchmarks for insecure IAM policies, open buckets, and unencrypted disks.',
    techStack: 'Python/Go, AWS Boto3/GCP SDKs, FastAPI, PostgreSQL, React, Docker',
    demonstrate: 'Policy-as-code engine (OPA/Rego), RBAC, automated security baseline audits, remediation workflows',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Go/Python, AWS SDK, Open Policy Agent, PostgreSQL',
    tags: ['CSPM', 'Cloud Security', 'CIS Benchmarks', 'OPA'],
    featured: true,
  },

  // ==========================================
  // 4. WEB DEVELOPMENT / FRONTEND (5 PROJECTS)
  // ==========================================
  {
    id: 'web-1',
    title: 'Accessible College Event Portal',
    domainId: 'frontend',
    domainName: 'Web Development / Frontend',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Responsive, WCAG-compliant college event catalog with ticket booking, speaker schedule, and organizer management dashboard.',
    techStack: 'React/Next.js, TypeScript, TailwindCSS/Vanilla CSS, REST API',
    demonstrate: 'Responsive UI, form validation, WCAG accessibility standards (a11y, ARIA tags, keyboard navigation)',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'React, TypeScript, CSS, REST APIs',
    tags: ['Accessibility', 'React', 'WCAG', 'Responsive Web'],
    featured: false,
  },
  {
    id: 'web-2',
    title: 'Personal Finance Dashboard',
    domainId: 'frontend',
    domainName: 'Web Development / Frontend',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Track personal cashflows, category budgets, monthly trends, and recurring subscriptions with interactive visual charts.',
    techStack: 'React, TypeScript, Chart.js/Recharts, LocalStorage or Mock API',
    demonstrate: 'Complex UI state management (Zustand/Context), interactive data visualization, clean financial metrics',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'React, TypeScript, Recharts, Zustand',
    tags: ['Data Viz', 'Finance', 'State Management', 'Chart.js'],
    featured: false,
  },
  {
    id: 'web-3',
    title: 'Multi-Vendor Service Marketplace Frontend',
    domainId: 'frontend',
    domainName: 'Web Development / Frontend',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Customers search verified service providers, compare reviews/pricing, schedule appointments, and track booking status.',
    techStack: 'React/Next.js, TypeScript, TanStack Query, REST APIs, Auth0/JWT',
    demonstrate: 'Faceted search filtering, multi-step booking forms, role-aware UI navigation, optimistic UI updates',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Next.js, TypeScript, TanStack Query, REST',
    tags: ['Marketplace', 'Next.js', 'Faceted Search', 'Forms'],
    featured: true,
  },
  {
    id: 'web-4',
    title: 'Real-Time Collaboration Board',
    domainId: 'frontend',
    domainName: 'Web Development / Frontend',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'A Kanban-style project workspace with drag-and-drop cards, live user cursor presence, and instant multi-user synchronization.',
    techStack: 'React, TypeScript, Node.js, WebSockets / Socket.io, PostgreSQL',
    demonstrate: 'Real-time state synchronization, drag-and-drop interactions, conflict handling, optimistic mutations',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'React, WebSockets, Socket.io, Node.js',
    tags: ['WebSockets', 'Kanban', 'Real-Time', 'Drag and Drop'],
    featured: false,
  },
  {
    id: 'web-5',
    title: 'Enterprise Workflow SaaS Frontend',
    domainId: 'frontend',
    domainName: 'Web Development / Frontend',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'TY / Final',
    problem: 'Highly configurable administrative dashboards, dynamic workflow builders, approval pipelines, and audit log exploration.',
    techStack: 'Next.js App Router, TypeScript, React Query, Custom Design System, WebSockets, Vitest/Playwright',
    demonstrate: 'Large-scale frontend architecture, granular permission matrices, web performance vitals (Core Web Vitals), E2E test suite',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Next.js, TypeScript, React Query, Playwright',
    tags: ['SaaS Frontend', 'Design System', 'Core Web Vitals', 'Testing'],
    featured: true,
  },

  // ==========================================
  // 5. FULL-STACK DEVELOPMENT (5 PROJECTS)
  // ==========================================
  {
    id: 'fs-1',
    title: 'Student Management System',
    domainId: 'fullstack',
    domainName: 'Full-Stack Development',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Manage student enrollment, course registration, attendance records, exam marks, and administrative grading reports.',
    techStack: 'React, Node.js/Express, MongoDB/PostgreSQL, JWT Authentication',
    demonstrate: 'Full CRUD operations, password hashing, JWT authentication, role-based dashboards (Admin/Faculty/Student)',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'React, Express, MongoDB, JWT',
    tags: ['CRUD', 'JWT Auth', 'Student Portal', 'MERN'],
    featured: false,
  },
  {
    id: 'fs-2',
    title: 'Hospital Appointment & Records Platform',
    domainId: 'fullstack',
    domainName: 'Full-Stack Development',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Patients book doctor consultation slots, clinicians manage appointment queues, and authorized personnel access encrypted medical notes.',
    techStack: 'React/Next.js, Node.js/NestJS, PostgreSQL, Redis, JWT',
    demonstrate: 'Granular RBAC, database ACID transactions, appointment conflict locking with Redis, audit logging',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Next.js, NestJS, PostgreSQL, Redis',
    tags: ['Healthcare', 'PostgreSQL Transactions', 'Redis Locking', 'NestJS'],
    featured: true,
  },
  {
    id: 'fs-3',
    title: 'B2B Inventory & Order Management SaaS',
    domainId: 'fullstack',
    domainName: 'Full-Stack Development',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Wholesale businesses manage multi-warehouse stock levels, purchase orders, customer invoices, and inventory reorder triggers.',
    techStack: 'React/Next.js, NestJS, PostgreSQL, Redis Caching, Docker',
    demonstrate: 'Multi-role workflows, transactional inventory consistency, low-stock webhook notifications, PDF invoice generation',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'NestJS, PostgreSQL, Redis, Docker, React',
    tags: ['Inventory SaaS', 'B2B', 'PostgreSQL', 'Webhooks'],
    featured: false,
  },
  {
    id: 'fs-4',
    title: 'FinTech-Style Expense & Cashflow Platform',
    domainId: 'fullstack',
    domainName: 'Full-Stack Development',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'TY / Final',
    problem: 'Track corporate invoices, expense approvals, payment reconciliations, and predictive cashflow forecast models.',
    techStack: 'Next.js, NestJS, PostgreSQL, Redis, Python microservice for forecasting, Docker Compose',
    demonstrate: 'Double-entry accounting schema, immutable financial audit logs, microservice API integration, automated export pipelines',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Next.js, NestJS, Python ML, Redis, PostgreSQL',
    tags: ['FinTech', 'Double Entry', 'Microservices', 'Audit Logs'],
    featured: true,
  },
  {
    id: 'fs-5',
    title: 'Multi-Tenant Business Operations SaaS',
    domainId: 'fullstack',
    domainName: 'Full-Stack Development',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Organizations manage team members, projects, billing subscriptions, and integrations in logically isolated tenant schemas.',
    techStack: 'Next.js, NestJS, PostgreSQL (Schema-per-tenant), Redis, BullMQ background queues, Docker/Kubernetes',
    demonstrate: 'Multi-tenancy data isolation, Stripe mock billing, async background report jobs, distributed tracing with OpenTelemetry',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Next.js, NestJS, PostgreSQL, BullMQ, Kubernetes',
    tags: ['Multi-Tenant', 'SaaS Architecture', 'BullMQ', 'Stripe Billing'],
    featured: true,
  },

  // ==========================================
  // 6. BACKEND / API ENGINEERING (5 PROJECTS)
  // ==========================================
  {
    id: 'be-1',
    title: 'Secure REST API Starter Platform',
    domainId: 'backend',
    domainName: 'Backend / API Engineering',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Production-ready starter boilerplate with authentication, input validation, role permissions, rate limiting, and OpenAPI docs.',
    techStack: 'Node.js/Express or FastAPI, PostgreSQL, JWT, Swagger/OpenAPI',
    demonstrate: 'RESTful API principles, schema validation (Zod/Joi), centralized error handling, Swagger documentation',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'Node.js, Express, PostgreSQL, Swagger',
    tags: ['REST API', 'Swagger', 'JWT', 'Boilerplate'],
    featured: false,
  },
  {
    id: 'be-2',
    title: 'Order Processing API with Idempotency',
    domainId: 'backend',
    domainName: 'Backend / API Engineering',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Process high-concurrency purchase orders, reserve warehouse stock, execute mock payments, and trigger asynchronous status alerts.',
    techStack: 'NestJS / Spring Boot, PostgreSQL, Redis, BullMQ / RabbitMQ',
    demonstrate: 'Database transactions, idempotent request handling (Idempotency-Key), distributed caching, background message queues',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'NestJS, Spring Boot, Redis, RabbitMQ, PostgreSQL',
    tags: ['Idempotency', 'Transactions', 'Redis Caching', 'Message Queues'],
    featured: true,
  },
  {
    id: 'be-3',
    title: 'Central Notification Microservice',
    domainId: 'backend',
    domainName: 'Backend / API Engineering',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Unified microservice to dispatch Email, SMS, and Push alerts with templating, exponential backoff retries, and rate limits.',
    techStack: 'Node.js/TypeScript, Redis, RabbitMQ/Kafka, PostgreSQL',
    demonstrate: 'Dead-letter queues, exponential retry policies, provider failover, token-bucket rate limiting',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'TypeScript, RabbitMQ, Redis, PostgreSQL',
    tags: ['Notifications', 'Dead Letter Queue', 'Rate Limiting', 'RabbitMQ'],
    featured: false,
  },
  {
    id: 'be-4',
    title: 'Event-Driven E-Commerce Backend',
    domainId: 'backend',
    domainName: 'Backend / API Engineering',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'TY / Final',
    problem: 'Decoupled microservices for Catalog, Order, Payment, and Shipping communicating asynchronously through event streams.',
    techStack: 'Java/Spring Boot or Node/NestJS, Apache Kafka, PostgreSQL, Redis, Docker',
    demonstrate: 'Event-Driven Architecture (EDA), Outbox Pattern, Saga pattern for distributed transactions, distributed tracing',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Spring Boot, Kafka, Docker, Redis, PostgreSQL',
    tags: ['Kafka', 'Event-Driven', 'Saga Pattern', 'Spring Boot'],
    featured: true,
  },
  {
    id: 'be-5',
    title: 'API Gateway & Service Mesh Platform',
    domainId: 'backend',
    domainName: 'Backend / API Engineering',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Reverse proxy gateway featuring JWT verification, token-bucket rate limiting, path routing, circuit breaker, and health metrics.',
    techStack: 'Go / Java / Node.js, Redis, Docker/Kubernetes, Prometheus & Grafana',
    demonstrate: 'Distributed systems routing, circuit breaker patterns (Resilience4j), dynamic service discovery, Prometheus metric collection',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Go, Redis, Kubernetes, Prometheus, Grafana',
    tags: ['API Gateway', 'Circuit Breaker', 'Service Mesh', 'Go'],
    featured: true,
  },

  // ==========================================
  // 7. DATA SCIENCE / ANALYTICS (5 PROJECTS)
  // ==========================================
  {
    id: 'ds-1',
    title: 'Student Performance Analytics',
    domainId: 'data-science',
    domainName: 'Data Science / Analytics',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Discover correlations between lecture attendance, internal test marks, and study hours to visualize academic risk factors.',
    techStack: 'Python, pandas, SQL, Matplotlib/Seaborn, Streamlit dashboard',
    demonstrate: 'Data cleaning, Exploratory Data Analysis (EDA), statistical summary charts, interactive dashboard filters',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'Python, pandas, Streamlit, Seaborn',
    tags: ['EDA', 'Streamlit', 'Data Cleaning', 'Analytics'],
    featured: false,
  },
  {
    id: 'ds-2',
    title: 'Retail Sales & Customer Analytics',
    domainId: 'data-science',
    domainName: 'Data Science / Analytics',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Analyze multi-store retail transactions across product categories, customer demographics, and seasonal sales periods.',
    techStack: 'Python, SQL, PostgreSQL, pandas, Plotly visualization',
    demonstrate: 'Complex SQL aggregations/window functions, RFM (Recency, Frequency, Monetary) customer segmentation, interactive graphs',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'Python, SQL, Plotly, PostgreSQL',
    tags: ['RFM Segmentation', 'SQL Analytics', 'Retail Data'],
    featured: false,
  },
  {
    id: 'ds-3',
    title: 'Business KPI Intelligence Dashboard',
    domainId: 'data-science',
    domainName: 'Data Science / Analytics',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Consolidate sales, customer churn, marketing attribution, and operational datasets into a real-time executive dashboard.',
    techStack: 'Python, SQL, PostgreSQL, Power BI / React, FastAPI backend',
    demonstrate: 'Automated ETL pipeline, KPI metric calculations (CAC, LTV, Churn Rate), role-based dashboard filtering',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Python, FastAPI, PostgreSQL, Power BI, React',
    tags: ['KPI Dashboard', 'ETL Pipeline', 'Business Intelligence'],
    featured: true,
  },
  {
    id: 'ds-4',
    title: 'Demand Forecasting & Inventory Optimization',
    domainId: 'data-science',
    domainName: 'Data Science / Analytics',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Forecast product inventory demand across regional warehouses using historical sales, promotional calendars, and seasonal patterns.',
    techStack: 'Python, pandas, statsmodels (ARIMA/Prophet), scikit-learn, FastAPI, React',
    demonstrate: 'Time series decomposition, cross-validation for time series, safety stock recommendation algorithms, prediction API',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Python, Prophet, ARIMA, FastAPI, React',
    tags: ['Demand Forecasting', 'Prophet', 'ARIMA', 'Time Series'],
    featured: false,
  },
  {
    id: 'ds-5',
    title: 'Enterprise Data Warehouse & Analytics Platform',
    domainId: 'data-science',
    domainName: 'Data Science / Analytics',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Ingest raw multi-source transactional data, orchestrate daily transform jobs, and expose governed data marts for enterprise BI.',
    techStack: 'Python, Apache Airflow, PostgreSQL / Snowflake, dbt (data build tool), Docker, Superset',
    demonstrate: 'Orchestrated ETL/ELT DAG pipelines, data quality testing (dbt tests), dimensional star-schema modeling, lineage tracking',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Airflow, dbt, PostgreSQL, Superset, Docker',
    tags: ['Data Engineering', 'Airflow', 'dbt', 'Star Schema', 'ETL'],
    featured: true,
  },

  // ==========================================
  // 8. CLOUD / DEVOPS / SRE (5 PROJECTS)
  // ==========================================
  {
    id: 'ops-1',
    title: 'Dockerized Full-Stack Web Deployment',
    domainId: 'devops',
    domainName: 'Cloud / DevOps / SRE',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Containerize frontend, backend, and PostgreSQL database with multi-stage Dockerfiles and deploy via Docker Compose.',
    techStack: 'Docker, Docker Compose, GitHub Actions, Node/React, PostgreSQL',
    demonstrate: 'Multi-stage Docker builds, container networking, persistent volumes, environment variable isolation',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'Docker, Docker Compose, GitHub Actions',
    tags: ['Docker', 'Multi-Stage Build', 'Containers', 'DevOps'],
    featured: false,
  },
  {
    id: 'ops-2',
    title: 'Automated CI/CD Pipeline with Zero-Downtime',
    domainId: 'devops',
    domainName: 'Cloud / DevOps / SRE',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Automate linting, unit testing, Docker image creation, security scanning (Trivy), and deployment to cloud VM with rollback capabilities.',
    techStack: 'GitHub Actions, Docker, Trivy security scanner, AWS EC2 / DigitalOcean, Nginx',
    demonstrate: 'CI/CD stages, secret management, vulnerability gating, blue-green / rolling deploy scripts',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'GitHub Actions, Trivy, Docker, Nginx, AWS',
    tags: ['CI/CD', 'GitHub Actions', 'Security Scanning', 'Zero Downtime'],
    featured: true,
  },
  {
    id: 'ops-3',
    title: 'Cloud Observability & Monitoring Dashboard',
    domainId: 'devops',
    domainName: 'Cloud / DevOps / SRE',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Collect application metrics, system CPU/memory stats, and request error logs; display live health and trigger Discord/Slack alerts.',
    techStack: 'Prometheus, Grafana, Node.js / Python Exporter, Docker, Alertmanager',
    demonstrate: 'Time-series metric collection, RED method (Rate, Errors, Duration) metrics, custom Grafana dashboards, alert rules',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Prometheus, Grafana, Alertmanager, Docker',
    tags: ['Observability', 'Prometheus', 'Grafana', 'SRE'],
    featured: false,
  },
  {
    id: 'ops-4',
    title: 'Kubernetes Microservice Cluster Platform',
    domainId: 'devops',
    domainName: 'Cloud / DevOps / SRE',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'TY / Final',
    problem: 'Orchestrate multiple microservices with Ingress controllers, Horizontal Pod Autoscaling (HPA), ConfigMaps/Secrets, and persistent storage.',
    techStack: 'Kubernetes (k8s / Minikube / EKS), Helm charts, Docker, Prometheus & Grafana, Nginx Ingress',
    demonstrate: 'Kubernetes manifests & Helm packaging, auto-scaling under load, rolling updates, health checks (liveness/readiness probes)',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Kubernetes, Helm, Docker, Ingress, AWS EKS',
    tags: ['Kubernetes', 'Helm', 'HPA', 'Microservices Cluster'],
    featured: true,
  },
  {
    id: 'ops-5',
    title: 'Internal Developer Platform (IDP) with IaC',
    domainId: 'devops',
    domainName: 'Cloud / DevOps / SRE',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Self-service developer portal allowing teams to provision cloud infrastructure, CI/CD pipelines, and microservice templates in minutes.',
    techStack: 'Terraform (IaC), Kubernetes, GitHub Actions, Backstage / Custom React Portal, AWS/GCP',
    demonstrate: 'Infrastructure as Code (Terraform), platform engineering patterns, automated policy guardrails, developer self-service golden paths',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Terraform, Kubernetes, GitHub Actions, AWS',
    tags: ['Platform Engineering', 'Terraform', 'IaC', 'IDP'],
    featured: true,
  },

  // ==========================================
  // 9. MOBILE / CROSS-PLATFORM (5 PROJECTS)
  // ==========================================
  {
    id: 'mob-1',
    title: 'Campus Companion Mobile App',
    domainId: 'mobile',
    domainName: 'Mobile / Cross-Platform',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'All-in-one student assistant app for daily timetables, live campus notices, interactive department maps, and personal assignment reminders.',
    techStack: 'Flutter / Dart or React Native, Firebase Auth & Firestore, Local Notifications',
    demonstrate: 'Mobile UI design, offline caching, push notifications, responsive cross-platform layout',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'Flutter, Firebase, Dart, Android/iOS',
    tags: ['Flutter', 'Mobile App', 'Firebase', 'Campus Life'],
    featured: false,
  },
  {
    id: 'mob-2',
    title: 'Medicine Reminder & Health Tracker App',
    domainId: 'mobile',
    domainName: 'Mobile / Cross-Platform',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Personal medication dosage schedule, refill alerts, doctor appointment booking, and vitals logging (demo/educational use).',
    techStack: 'Flutter / React Native, Node.js / FastAPI, PostgreSQL, SQLite, Background Worker',
    demonstrate: 'Accurate background alarms, SQLite offline storage, secure REST synchronization, HIPAA-aware UI design',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Flutter, SQLite, Node.js, PostgreSQL',
    tags: ['Health Tech', 'Background Alarms', 'Offline First', 'Flutter'],
    featured: false,
  },
  {
    id: 'mob-3',
    title: 'Field Sales & Route Management App',
    domainId: 'mobile',
    domainName: 'Mobile / Cross-Platform',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Field sales agents manage client visit schedules, log order bookings offline in low-connectivity areas, and sync on reconnection.',
    techStack: 'Flutter / React Native, SQLite / WatermelonDB, Node.js, PostgreSQL, Google Maps API',
    demonstrate: 'Offline-first database architecture, bidirectional delta sync, GPS location verification, camera attachment uploads',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'React Native, SQLite, Node.js, Google Maps',
    tags: ['Offline First', 'Field Sales', 'GPS Sync', 'React Native'],
    featured: true,
  },
  {
    id: 'mob-4',
    title: 'Last-Mile Delivery Driver & Customer Suite',
    domainId: 'mobile',
    domainName: 'Mobile / Cross-Platform',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'TY / Final',
    problem: 'Dual mobile application ecosystem for customers and delivery drivers featuring live GPS route tracking, status updates, and digital signature proof.',
    techStack: 'Flutter, Node.js / NestJS, PostgreSQL, Redis, WebSockets, Google Maps SDK',
    demonstrate: 'Real-time WebSocket geospatial broadcasting, background driver location service, digital signature capture, push alerts',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Flutter, NestJS, Redis Geospatial, WebSockets',
    tags: ['Delivery App', 'Geospatial', 'WebSockets', 'Real-Time Tracking'],
    featured: true,
  },
  {
    id: 'mob-5',
    title: 'IoT Fleet Telemetry & Remote Control App',
    domainId: 'mobile',
    domainName: 'Mobile / Cross-Platform',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Mobile command application for connected hardware devices with live sensor streams, critical telemetry threshold alerts, and remote reboot actions.',
    techStack: 'Flutter, MQTT protocol, Node.js / Python, PostgreSQL / TimescaleDB, Docker',
    demonstrate: 'Low-latency MQTT broker integration over WebSockets, live time-series chart rendering, cryptographic device identity verification',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Flutter, MQTT, TimescaleDB, Node.js',
    tags: ['IoT Mobile', 'MQTT', 'TimescaleDB', 'Hardware Telemetry'],
    featured: true,
  },

  // ==========================================
  // 10. IOT / EDGE / EMBEDDED SYSTEMS (5 PROJECTS)
  // ==========================================
  {
    id: 'iot-1',
    title: 'Smart Energy & Power Monitor',
    domainId: 'iot',
    domainName: 'IoT / Edge / Embedded',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Sample real-time power and voltage sensor readings from home appliances and visualize daily energy consumption patterns on a dashboard.',
    techStack: 'ESP32 / Arduino, C/C++, MQTT protocol, Node.js backend, React web dashboard',
    demonstrate: 'Microcontroller sensor reading (ADC), MQTT publisher-subscriber messaging, real-time web socket dashboard update',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'ESP32, C/C++, MQTT, Node.js, React',
    tags: ['ESP32', 'Energy Monitor', 'MQTT', 'Hardware'],
    featured: false,
  },
  {
    id: 'iot-2',
    title: 'Smart Plant Irrigation & Soil Monitor',
    domainId: 'iot',
    domainName: 'IoT / Edge / Embedded',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Continuously measure soil moisture, temperature, and ambient light; automatically activate a water pump relay and send Telegram/email notifications.',
    techStack: 'ESP32, C++, capacitive sensors, MQTT, Python / Node.js, Telegram Bot API',
    demonstrate: 'Hardware threshold logic, relay actuator control, low-power deep sleep modes, automated messaging bots',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'ESP32, C++, MQTT, Telegram API',
    tags: ['Smart Agriculture', 'ESP32', 'Relay Control', 'IoT'],
    featured: false,
  },
  {
    id: 'iot-3',
    title: 'Cold-Chain Pharmaceutical Temperature Monitor',
    domainId: 'iot',
    domainName: 'IoT / Edge / Embedded',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Monitor temperature and humidity inside pharmaceutical storage or transport vans, recording immutable logs and sounding alerts upon temperature excursions.',
    techStack: 'ESP32, DHT22 / DS18B20 sensors, MQTT, Node.js, PostgreSQL, React',
    demonstrate: 'Edge data validation, network loss buffering (EEPROM/SD card), automated compliance alert triggers',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'ESP32, MQTT, PostgreSQL, Node.js, React',
    tags: ['Cold Chain', 'Pharma Tech', 'Sensors', 'Compliance'],
    featured: false,
  },
  {
    id: 'iot-4',
    title: 'Industrial Machine Health & Vibration Analyzer',
    domainId: 'iot',
    domainName: 'IoT / Edge / Embedded',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Collect high-frequency accelerometer vibration data from industrial motors to compute FFT features and detect mechanical imbalance.',
    techStack: 'ESP32 / Edge Linux (Raspberry Pi), Python, MQTT, Scikit-learn Anomaly Detection, TimescaleDB, React',
    demonstrate: 'Edge signal processing (FFT / vibration analysis), lightweight ML anomaly detection, time-series telemetry storage',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Python, Raspberry Pi, TimescaleDB, Scikit-learn',
    tags: ['Edge AI', 'Vibration Analysis', 'Industry 4.0', 'Raspberry Pi'],
    featured: true,
  },
  {
    id: 'iot-5',
    title: 'Smart Factory Digital Twin & Telemetry Platform',
    domainId: 'iot',
    domainName: 'IoT / Edge / Embedded',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Digitally mirror an assembly line with live 3D sensor telemetry, operational state simulation, predictive bottleneck alerts, and remote setpoint adjustments.',
    techStack: 'IoT Edge Gateways, MQTT / OPC-UA, Python / Node.js, React Three Fiber (3D WebGL), TimescaleDB, Docker',
    demonstrate: 'Digital Twin architecture, high-throughput MQTT ingestion, real-time 3D state visualization (Three.js), end-to-end device security',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Three.js, MQTT, TimescaleDB, Node.js, Docker',
    tags: ['Digital Twin', 'Three.js 3D', 'Smart Factory', 'OPC-UA'],
    featured: true,
  },

  // ==========================================
  // 11. BLOCKCHAIN / WEB3 (5 PROJECTS)
  // ==========================================
  {
    id: 'bc-1',
    title: 'Academic Certificate Verification DApp',
    domainId: 'blockchain',
    domainName: 'Blockchain / Web3',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Issue and verify tamper-proof university graduation certificates on an EVM blockchain testnet to eliminate credential fraud.',
    techStack: 'Solidity, Ethereum Sepolia Testnet, Hardhat, React, ethers.js / wagmi',
    demonstrate: 'Smart contract development, cryptographic hashing of credentials, Metamask wallet integration, decentralized verification',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'Solidity, Hardhat, React, Ethers.js',
    tags: ['Smart Contracts', 'Certificate Verification', 'Solidity', 'Web3'],
    featured: false,
  },
  {
    id: 'bc-2',
    title: 'Transparent Charity Donation Ledger',
    domainId: 'blockchain',
    domainName: 'Blockchain / Web3',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Record public charity donation events and milestone releases in an immutable, auditable smart contract demonstration.',
    techStack: 'Solidity, React, Node.js, Hardhat, Ethers.js',
    demonstrate: 'Payable smart contract functions, event emission indexing, public explorer verification',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'Solidity, Hardhat, Ethers.js, React',
    tags: ['Charity Ledger', 'Smart Contracts', 'Transparency'],
    featured: false,
  },
  {
    id: 'bc-3',
    title: 'Supply Chain Provenance & Traceability Demo',
    domainId: 'blockchain',
    domainName: 'Blockchain / Web3',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Track physical product ownership transfer from manufacturer to distributor to retailer with cryptographic signature proofs.',
    techStack: 'Solidity, React/Next.js, Node.js, PostgreSQL for off-chain metadata, IPFS',
    demonstrate: 'Hybrid on-chain/off-chain architecture, IPFS decentralized asset storage, role-based contract state transitions',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Solidity, IPFS, Next.js, PostgreSQL, Hardhat',
    tags: ['Supply Chain', 'IPFS', 'Provenance', 'Hybrid Web3'],
    featured: true,
  },
  {
    id: 'bc-4',
    title: 'Token-Gated Community & Resource Platform',
    domainId: 'blockchain',
    domainName: 'Blockchain / Web3',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Grant exclusive access to engineering research papers and courses based on cryptographic verification of user NFT / token holdings.',
    techStack: 'Solidity (ERC-721/1155), React/Next.js, TypeScript, Sign-In With Ethereum (SIWE), Express.js',
    demonstrate: 'Web3 cryptographic signature authentication (SIWE), smart contract verification backend middleware, token-gated routes',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Next.js, Solidity, SIWE, Ethers.js',
    tags: ['Token Gating', 'SIWE', 'ERC-721', 'Authentication'],
    featured: false,
  },
  {
    id: 'bc-5',
    title: 'Enterprise Asset Provenance & Verifiable Claims',
    domainId: 'blockchain',
    domainName: 'Blockchain / Web3',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Combine enterprise off-chain database transactions with cryptographic Merkle tree root anchors on-chain for privacy-preserving auditing.',
    techStack: 'Solidity, Node.js / NestJS, PostgreSQL, React, Merkle Proofs, Cloud Infrastructure',
    demonstrate: 'Merkle tree root state verification, privacy preservation for enterprise data, verifiable credentials, gas optimization',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Solidity, Merkle Trees, NestJS, PostgreSQL, Docker',
    tags: ['Merkle Proofs', 'Enterprise Blockchain', 'Zero Knowledge Concepts', 'Auditability'],
    featured: true,
  },

  // ==========================================
  // 12. SOFTWARE ENGINEERING / SYSTEM DESIGN (5 PROJECTS)
  // ==========================================
  {
    id: 'se-1',
    title: 'Project Management API & Team Dashboard',
    domainId: 'system-design',
    domainName: 'Software Engg / System Design',
    difficulty: 'LOW',
    difficultyLabel: 'Low (1–3 Weeks)',
    yearFit: 'FY / SY',
    problem: 'Create project sprints, assign tasks, write comments, track statuses, and view clean velocity burn-down metrics.',
    techStack: 'React, Node.js / NestJS, PostgreSQL, Jest Unit Tests',
    demonstrate: 'Clean Layered Architecture (Controller-Service-Repository), unit testing with Jest, schema relationships',
    scope: 'MVP with clean UI, authentication where needed, database and README.',
    industryStack: 'React, NestJS, PostgreSQL, Jest',
    tags: ['Clean Architecture', 'Unit Testing', 'Project Manager', 'Jest'],
    featured: false,
  },
  {
    id: 'se-2',
    title: 'High-Throughput Scalable URL Shortener',
    domainId: 'system-design',
    domainName: 'Software Engg / System Design',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Generate compact unique 7-character URLs, perform sub-5ms redirection lookups, track click telemetry, and enforce rate abuse controls.',
    techStack: 'Go / Node.js / Java, Redis Caching, PostgreSQL, Base62 Encoding, Docker',
    demonstrate: 'Base62 distributed key generation, Cache-Aside pattern (Redis), sliding-window rate limiting, redirect analytics',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Go / Node.js, Redis, PostgreSQL, Docker',
    tags: ['URL Shortener', 'System Design', 'Redis Cache', 'Base62'],
    featured: true,
  },
  {
    id: 'se-3',
    title: 'Concurrent Online Examination Platform',
    domainId: 'system-design',
    domainName: 'Software Engg / System Design',
    difficulty: 'MEDIUM',
    difficultyLabel: 'Medium (3–8 Weeks)',
    yearFit: 'SY / TY',
    problem: 'Host timed simultaneous exams for thousands of students with auto-save drafts, randomized question orders, and anti-cheat tab alerts.',
    techStack: 'React, Spring Boot / NestJS, PostgreSQL, Redis, WebSockets',
    demonstrate: 'High-concurrency submission handling, pessimistic locking on answer submissions, heartbeat anti-cheat logging, automated evaluation',
    scope: 'Production-style API, role-based access, validation, tests, deployment and monitoring basics.',
    industryStack: 'Spring Boot, PostgreSQL, Redis, React',
    tags: ['Concurrency', 'Exam Engine', 'Spring Boot', 'Pessimistic Lock'],
    featured: false,
  },
  {
    id: 'se-4',
    title: 'Ride / Delivery Dispatch & Geospatial Matcher',
    domainId: 'system-design',
    domainName: 'Software Engg / System Design',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'TY / Final',
    problem: 'Match incoming customer ride/delivery requests to the closest available drivers using spatial proximity and dynamic surge pricing algorithms.',
    techStack: 'Java / Go / Node.js, Redis (GEO commands), PostgreSQL (PostGIS), WebSockets, React Dashboard',
    demonstrate: 'Spatial QuadTree / Redis GEO spatial indexing, Hungarian matching algorithm, real-time WebSocket state distribution',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Go, PostGIS, Redis Geo, WebSockets, React',
    tags: ['Geospatial Matcher', 'System Design', 'Redis GEO', 'PostGIS'],
    featured: true,
  },
  {
    id: 'se-5',
    title: 'Distributed Job Scheduling & Worker Platform',
    domainId: 'system-design',
    domainName: 'Software Engg / System Design',
    difficulty: 'HIGH',
    difficultyLabel: 'High (2–5+ Months)',
    yearFit: 'Final Year Capstone',
    problem: 'Submit delayed/cron background jobs, distribute tasks across worker nodes, automatically retry failures, and prevent duplicate executions.',
    techStack: 'Go / Java / Node.js, Kafka / RabbitMQ, Redis Distributed Locks (Redlock), PostgreSQL, Docker/Kubernetes',
    demonstrate: 'Distributed lock coordination (Redlock), leader election, at-least-once delivery with idempotent execution, Prometheus health telemetry',
    scope: 'Architecture diagram, scalable backend, security controls, observability, CI/CD and load/error testing.',
    industryStack: 'Go, Kafka, Redis Redlock, Kubernetes, Prometheus',
    tags: ['Distributed Systems', 'Job Scheduler', 'Redlock', 'Kafka'],
    featured: true,
  },
];

export const DIFFICULTY_SPECS = [
  {
    level: 'LOW',
    color: '#10b981',
    badgeText: '🟢 LOW Difficulty',
    timeframe: '1–3 Weeks',
    techCount: '1–2 Major Technologies',
    summary: 'Beginner-friendly project focused on solid fundamentals, clean UI, and GitHub hygiene.',
    scopeChecklist: [
      'Clean, responsive user interface without broken styles',
      'Solid CRUD functionality with clean code and no hardcoded secrets',
      'Basic authentication & authorization where appropriate',
      'Clear project README with architecture summary and setup instructions',
    ],
  },
  {
    level: 'MEDIUM',
    color: '#f59e0b',
    badgeText: '🟡 MEDIUM Difficulty',
    timeframe: '3–8 Weeks',
    techCount: 'Full Stack & APIs & DB',
    summary: 'Intermediate production-style project featuring database design, role-based access, caching, and testing.',
    scopeChecklist: [
      'Production-style REST/GraphQL API with schema validation',
      'Relational / NoSQL database with migrations and indexing',
      'Role-Based Access Control (RBAC) with secure JWT/session auth',
      'Automated unit/integration tests with CI workflow',
      'Containerized environment with Docker and basic monitoring',
    ],
  },
  {
    level: 'HIGH',
    color: '#ef4444',
    badgeText: '🔴 HIGH Difficulty',
    timeframe: '2–5+ Months',
    techCount: 'Distributed & Scalable',
    summary: 'Advanced engineering project demonstrating architecture patterns, security, observability, and production reliability.',
    scopeChecklist: [
      'Detailed System Architecture diagram and trade-off justification',
      'High-throughput backend with message queues (Kafka/RabbitMQ) or caching (Redis)',
      'Robust security controls, input sanitization, and data audit logs',
      'Observability suite with metrics (Prometheus/Grafana) and structured logs',
      'Continuous Deployment (CI/CD) and automated stress/load testing',
    ],
  },
];

export const CAREER_PROGRESSION_RULES = [
  {
    year: '1st Year (FY)',
    stage: 'Foundation Stage',
    recommendation: 'Pick LOW projects in programming, web, basic databases, or simple IoT.',
    focus: 'Focus on fundamentals, clean Git commits, GitHub repository hygiene, and building confidence.',
    targetCount: '2–3 Small Projects',
    badgeColor: '#3b82f6',
  },
  {
    year: '2nd Year (SY)',
    stage: 'Core CSE Stage',
    recommendation: 'Pick MEDIUM projects in DSA, DBMS, OS/CN concepts, and backend/full-stack.',
    focus: 'Learn schema normalization, API validation, testing, containerization with Docker, and deployment.',
    targetCount: '2 Solid Medium Projects',
    badgeColor: '#8b5cf6',
  },
  {
    year: '3rd Year (TY)',
    stage: 'Specialization Stage',
    recommendation: 'Pick one domain (AI/ML, Cloud, Web, Security, Data) and build 1 MEDIUM + 1 HIGH project.',
    focus: 'Incorporate cloud deployment, security best practices, scalable APIs, and performance optimization.',
    targetCount: '1 Medium + 1 High Tier Project',
    badgeColor: '#10b981',
  },
  {
    year: '4th Year (Final)',
    stage: 'Industry Capstone Stage',
    recommendation: 'Build 1 flagship HIGH project as your major capstone project.',
    focus: 'Complete end-to-end SDLC: requirements, architecture diagrams, database design, testing, CI/CD, documentation & viva prep.',
    targetCount: '1 Major High-Impact Capstone',
    badgeColor: '#f97316',
  },
];

export const PORTFOLIO_FORMULA = {
  title: 'The Winning CSE Resume Portfolio Formula',
  formulaItems: [
    { count: '1 ×', title: 'LOW Project', desc: 'Proves core programming fundamentals & fast prototyping' },
    { count: '2 ×', title: 'MEDIUM Projects', desc: 'Proves practical full-stack, database & API engineering maturity' },
    { count: '1 ×', title: 'HIGH Specialization Project', desc: 'Proves deep domain expertise (AI/Cloud/Security/Systems)' },
    { count: '1 ×', title: 'Major Final-Year Capstone', desc: 'Proves end-to-end engineering ownership, testing & architecture' },
  ],
  deliverables: [
    'Public GitHub repository with frequent, clean commit history',
    'Live deployed web demo / API endpoint with test credentials',
    'Clean system architecture and database entity-relationship (ER) diagrams',
    'Interactive OpenAPI / Swagger documentation',
    'Automated test suite (Jest/Pytest/Vitest) with CI status badge',
    'Comprehensive README with technical trade-offs & local setup instructions',
  ],
};
