// ========================================================
// CSE 4-YEAR COURSERA CERTIFICATE GUIDE - DATA REPOSITORY
// Resume-Friendly Courses • Subject-wise • FY → SY → TY → Final Year
// ========================================================

export const COURSERA_TRACKS = [
  {
    id: 'ALL',
    name: 'All Tracks',
    icon: 'Compass',
    stage: 'All Years (FY to Final)',
    skills: 'Complete 35 Curated Certifications',
    count: 35,
  },
  {
    id: 'Core CSE Foundation',
    name: 'Core CSE Foundation',
    icon: 'Cpu',
    stage: 'FY–SY',
    skills: 'Programming, DSA, DBMS, OS, Networks, Git',
    description: 'Build rigorous academic foundations that power coding interviews and core computer science understanding.',
  },
  {
    id: 'Software Development',
    name: 'Software Development',
    icon: 'Code',
    stage: 'SY–TY',
    skills: 'Full Stack, Front-End, Back-End, Java, SQL',
    description: 'Learn modern industry stacks, front-end & back-end architectures, and production-level database management.',
  },
  {
    id: 'AI / Data',
    name: 'AI / Data',
    icon: 'Brain',
    stage: 'TY–Final',
    skills: 'Python, Data Science, ML, Deep Learning, GenAI',
    description: 'Master linear algebra, calculus, classical ML models, deep neural networks, and modern generative AI/LLMs.',
  },
  {
    id: 'Cloud / DevOps',
    name: 'Cloud / DevOps',
    icon: 'Server',
    stage: 'TY–Final',
    skills: 'Cloud, Docker, Kubernetes, CI/CD, AWS, GCP',
    description: 'Deploy, scale, and automate cloud infrastructure using AWS, Google Cloud, Docker, and CI/CD pipelines.',
  },
  {
    id: 'Cybersecurity',
    name: 'Cybersecurity',
    icon: 'Shield',
    stage: 'TY–Final',
    skills: 'Networking, security fundamentals, SOC/web security, SIEM',
    description: 'Understand defensive security, network packet analysis, SIEM tools, and security operations center workflows.',
  },
  {
    id: 'Career / Engineering',
    name: 'Career / Engineering',
    icon: 'Briefcase',
    stage: 'Final',
    skills: 'Software architecture, system design, Agile, IT support',
    description: 'Prepare for enterprise software architecture, scalable system design, Agile delivery, and technical interviews.',
  },
];

export const COURSERA_COURSES = [
  // ----------------------------------------------------
  // FIRST YEAR (FY) - BUILD THE FOUNDATION
  // ----------------------------------------------------
  {
    id: 1,
    title: 'Google IT Automation with Python Professional Certificate',
    year: 'FY',
    yearLabel: '1st Year (FY)',
    subject: 'Programming / Python',
    provider: 'Google',
    track: 'Core CSE Foundation',
    category: 'CoreCS',
    rating: 4.8,
    estimatedHours: '120 hrs (6 courses)',
    level: 'Beginner to Intermediate',
    whyUseful: 'Strong beginner-to-intermediate Python + automation + Git/GitHub/Linux foundation.',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-it-automation',
    searchUrl: 'https://www.coursera.org/search?query=Google%20IT%20Automation%20with%20Python',
    keySkills: ['Python', 'Git & GitHub', 'Linux CLI', 'Automation', 'Troubleshooting'],
    badgeColor: '#10b981',
    isSpecialization: true,
  },
  {
    id: 2,
    title: 'Programming for Everybody (Getting Started with Python)',
    year: 'FY',
    yearLabel: '1st Year (FY)',
    subject: 'Python / Programming',
    provider: 'University of Michigan',
    track: 'Core CSE Foundation',
    category: 'CoreCS',
    rating: 4.8,
    estimatedHours: '19 hrs',
    level: 'Beginner',
    whyUseful: 'Beginner-friendly Python foundation; useful if Python is new.',
    courseUrl: 'https://www.coursera.org/learn/python',
    searchUrl: 'https://www.coursera.org/search?query=Programming%20for%20Everybody%20Getting%20Started%20with%20Python',
    keySkills: ['Python Syntax', 'Variables & Loops', 'Functions', 'Problem Solving'],
    badgeColor: '#3b82f6',
    isSpecialization: false,
  },
  {
    id: 3,
    title: 'HTML, CSS, and Javascript for Web Developers',
    year: 'FY',
    yearLabel: '1st Year (FY)',
    subject: 'Web Development',
    provider: 'Johns Hopkins University',
    track: 'Software Development',
    category: 'FullStack',
    rating: 4.7,
    estimatedHours: '40 hrs',
    level: 'Beginner',
    whyUseful: 'Builds core web fundamentals before frameworks.',
    courseUrl: 'https://www.coursera.org/learn/html-css-javascript-for-web-developers',
    searchUrl: 'https://www.coursera.org/search?query=HTML%20CSS%20Javascript%20for%20Web%20Developers',
    keySkills: ['HTML5', 'CSS3', 'JavaScript Basics', 'Responsive Layout', 'DOM Manipulation'],
    badgeColor: '#ec4899',
    isSpecialization: false,
  },
  {
    id: 4,
    title: 'Introduction to Git and GitHub',
    year: 'FY',
    yearLabel: '1st Year (FY)',
    subject: 'Git / Version Control',
    provider: 'IBM',
    track: 'Core CSE Foundation',
    category: 'CoreCS',
    rating: 4.7,
    estimatedHours: '12 hrs',
    level: 'Beginner',
    whyUseful: 'Practical Git/GitHub workflow for repositories and collaboration.',
    courseUrl: 'https://www.coursera.org/learn/introduction-git-github',
    searchUrl: 'https://www.coursera.org/search?query=Introduction%20to%20Git%20and%20GitHub%20IBM',
    keySkills: ['Git Commits', 'Branching & Merging', 'GitHub Repositories', 'Pull Requests'],
    badgeColor: '#6366f1',
    isSpecialization: false,
  },
  {
    id: 5,
    title: 'The Bits and Bytes of Computer Networking',
    year: 'FY',
    yearLabel: '1st Year (FY)',
    subject: 'Computer Networking',
    provider: 'Google',
    track: 'Core CSE Foundation',
    category: 'CoreCS',
    rating: 4.8,
    estimatedHours: '34 hrs',
    level: 'Beginner',
    whyUseful: 'Good introduction to networking concepts before deeper CN study.',
    courseUrl: 'https://www.coursera.org/learn/computer-networking',
    searchUrl: 'https://www.coursera.org/search?query=The%20Bits%20and%20Bytes%20of%20Computer%20Networking',
    keySkills: ['TCP/IP', 'DNS & DHCP', 'Subnetting', 'Routing', 'Network Layers'],
    badgeColor: '#10b981',
    isSpecialization: false,
  },
  {
    id: 6,
    title: 'Operating Systems and You: Becoming a Power User',
    year: 'FY',
    yearLabel: '1st Year (FY)',
    subject: 'Linux / OS Foundation',
    provider: 'Google',
    track: 'Core CSE Foundation',
    category: 'CoreCS',
    rating: 4.7,
    estimatedHours: '35 hrs',
    level: 'Beginner',
    whyUseful: 'Introduces OS concepts, processes, memory, files and command-line skills.',
    courseUrl: 'https://www.coursera.org/learn/os-power-user',
    searchUrl: 'https://www.coursera.org/search?query=Operating%20Systems%20and%20You%20Becoming%20a%20Power%20User',
    keySkills: ['Linux CLI', 'Process Management', 'File Systems', 'Disk Partitioning', 'PowerShell'],
    badgeColor: '#10b981',
    isSpecialization: false,
  },
  {
    id: 7,
    title: 'Mathematics for Machine Learning: Linear Algebra',
    year: 'FY',
    yearLabel: '1st Year (FY)',
    subject: 'Math / Linear Algebra',
    provider: 'Imperial College London',
    track: 'AI / Data',
    category: 'AI_ML',
    rating: 4.7,
    estimatedHours: '19 hrs',
    level: 'Intermediate',
    whyUseful: 'Useful mathematical foundation for later ML/AI study.',
    courseUrl: 'https://www.coursera.org/learn/linear-algebra-machine-learning',
    searchUrl: 'https://www.coursera.org/search?query=Mathematics%20for%20Machine%20Learning%20Linear%20Algebra',
    keySkills: ['Vectors & Matrices', 'Eigenvalues & Eigenvectors', 'Matrix Transformations', 'PageRank'],
    badgeColor: '#8b5cf6',
    isSpecialization: false,
  },
  {
    id: 8,
    title: 'Mathematics for Machine Learning: Multivariate Calculus',
    year: 'FY',
    yearLabel: '1st Year (FY)',
    subject: 'Math / Calculus',
    provider: 'Imperial College London',
    track: 'AI / Data',
    category: 'AI_ML',
    rating: 4.7,
    estimatedHours: '18 hrs',
    level: 'Intermediate',
    whyUseful: 'Calculus concepts useful for ML foundations.',
    courseUrl: 'https://www.coursera.org/learn/multivariate-calculus-machine-learning',
    searchUrl: 'https://www.coursera.org/search?query=Mathematics%20for%20Machine%20Learning%20Multivariate%20Calculus',
    keySkills: ['Gradients', 'Jacobian & Hessian', 'Optimization', 'Neural Network Backprop Math'],
    badgeColor: '#8b5cf6',
    isSpecialization: false,
  },

  // ----------------------------------------------------
  // SECOND YEAR (SY) - CORE COMPUTER SCIENCE
  // ----------------------------------------------------
  {
    id: 9,
    title: 'Algorithms, Part I',
    year: 'SY',
    yearLabel: '2nd Year (SY)',
    subject: 'DSA',
    provider: 'Princeton University',
    track: 'Core CSE Foundation',
    category: 'Algorithms',
    rating: 4.9,
    estimatedHours: '54 hrs',
    level: 'Intermediate',
    whyUseful: 'University-level algorithms and data structures foundation; strong for DSA depth.',
    courseUrl: 'https://www.coursera.org/learn/algorithms-part1',
    searchUrl: 'https://www.coursera.org/search?query=Algorithms%20Part%20I%20Princeton',
    keySkills: ['Union-Find', 'Stacks & Queues', 'Sorting (Quicksort/Mergesort)', 'Priority Queues', 'BSTs'],
    badgeColor: '#f59e0b',
    isSpecialization: false,
    isShortlist: true,
  },
  {
    id: 10,
    title: 'Algorithms, Part II',
    year: 'SY',
    yearLabel: '2nd Year (SY)',
    subject: 'DSA',
    provider: 'Princeton University',
    track: 'Core CSE Foundation',
    category: 'Algorithms',
    rating: 4.9,
    estimatedHours: '58 hrs',
    level: 'Advanced',
    whyUseful: 'Advanced graph and algorithm topics following Part I.',
    courseUrl: 'https://www.coursera.org/learn/algorithms-part2',
    searchUrl: 'https://www.coursera.org/search?query=Algorithms%20Part%20II%20Princeton',
    keySkills: ['Graph Algorithms (BFS/DFS)', 'Shortest Paths (Dijkstra)', 'Max Flow/Min Cut', 'Radix Sorts', 'Tries & Compression'],
    badgeColor: '#f59e0b',
    isSpecialization: false,
    isShortlist: true,
  },
  {
    id: 11,
    title: 'Object Oriented Programming in Java Specialization',
    year: 'SY',
    yearLabel: '2nd Year (SY)',
    subject: 'OOP / Java',
    provider: 'Duke University',
    track: 'Software Development',
    category: 'FullStack',
    rating: 4.7,
    estimatedHours: '80 hrs (5 courses)',
    level: 'Beginner to Intermediate',
    whyUseful: 'Java + OOP + software design through a multi-course specialization.',
    courseUrl: 'https://www.coursera.org/specializations/object-oriented-programming',
    searchUrl: 'https://www.coursera.org/search?query=Object%20Oriented%20Programming%20in%20Java%20Duke',
    keySkills: ['Java OOP', 'Inheritance & Polymorphism', 'Data Structures in Java', 'Software Design', 'GUI & Visualization'],
    badgeColor: '#0ea5e9',
    isSpecialization: true,
    isShortlist: true,
  },
  {
    id: 12,
    title: 'Introduction to Relational Databases',
    year: 'SY',
    yearLabel: '2nd Year (SY)',
    subject: 'DBMS / SQL',
    provider: 'IBM',
    track: 'Core CSE Foundation',
    category: 'CoreCS',
    rating: 4.6,
    estimatedHours: '15 hrs',
    level: 'Beginner',
    whyUseful: 'Relational database concepts and SQL foundation.',
    courseUrl: 'https://www.coursera.org/learn/introduction-to-relational-databases',
    searchUrl: 'https://www.coursera.org/search?query=Introduction%20to%20Relational%20Databases%20IBM',
    keySkills: ['RDBMS Concepts', 'Tables & Keys', 'SQL DDL/DML', 'Relational Models'],
    badgeColor: '#6366f1',
    isSpecialization: false,
  },
  {
    id: 13,
    title: 'Databases and SQL for Data Science with Python',
    year: 'SY',
    yearLabel: '2nd Year (SY)',
    subject: 'SQL / Data',
    provider: 'IBM',
    track: 'AI / Data',
    category: 'DataScience',
    rating: 4.7,
    estimatedHours: '38 hrs',
    level: 'Beginner to Intermediate',
    whyUseful: 'Practical SQL plus Python/data workflow; useful beyond academic DBMS.',
    courseUrl: 'https://www.coursera.org/learn/sql-data-science',
    searchUrl: 'https://www.coursera.org/search?query=Databases%20and%20SQL%20for%20Data%20Science%20with%20Python',
    keySkills: ['SQL Queries & Joins', 'Python DB-API', 'Pandas SQL Integration', 'Stored Procedures'],
    badgeColor: '#6366f1',
    isSpecialization: false,
  },
  {
    id: 14,
    title: 'Computer Communications Specialization',
    year: 'SY',
    yearLabel: '2nd Year (SY)',
    subject: 'Networking',
    provider: 'University of Colorado System',
    track: 'Core CSE Foundation',
    category: 'CoreCS',
    rating: 4.6,
    estimatedHours: '50 hrs (3 courses)',
    level: 'Intermediate',
    whyUseful: 'Deeper networking concepts and practical communication systems.',
    courseUrl: 'https://www.coursera.org/specializations/computer-communications',
    searchUrl: 'https://www.coursera.org/search?query=Computer%20Communications%20Specialization',
    keySkills: ['Packet Switching', 'TCP Congestion Control', 'Routing Algorithms', 'Network Security', 'Socket Programming'],
    badgeColor: '#0ea5e9',
    isSpecialization: true,
  },
  {
    id: 15,
    title: 'Operating Systems and You: Becoming a Power User (Reinforcement)',
    year: 'SY',
    yearLabel: '2nd Year (SY)',
    subject: 'OS / Systems',
    provider: 'Google',
    track: 'Core CSE Foundation',
    category: 'CoreCS',
    rating: 4.7,
    estimatedHours: '35 hrs',
    level: 'Intermediate',
    whyUseful: 'Useful reinforcement for OS and Linux/system concepts.',
    courseUrl: 'https://www.coursera.org/learn/os-power-user',
    searchUrl: 'https://www.coursera.org/search?query=Operating%20Systems%20and%20You',
    keySkills: ['Process Scheduling', 'Virtual Memory', 'System Logs', 'Shell Scripting'],
    badgeColor: '#10b981',
    isSpecialization: false,
  },
  {
    id: 16,
    title: 'Version Control with Git',
    year: 'SY',
    yearLabel: '2nd Year (SY)',
    subject: 'Git / Engineering',
    provider: 'Atlassian',
    track: 'Software Development',
    category: 'FullStack',
    rating: 4.7,
    estimatedHours: '15 hrs',
    level: 'Intermediate',
    whyUseful: 'Version control practices relevant to team software development.',
    courseUrl: 'https://www.coursera.org/learn/version-control-with-git',
    searchUrl: 'https://www.coursera.org/search?query=Version%20Control%20with%20Git%20Atlassian',
    keySkills: ['Git Workflows', 'Rebase & Merge Conflicts', 'Tagging & Releases', 'Team Collaboration'],
    badgeColor: '#3b82f6',
    isSpecialization: false,
  },

  // ----------------------------------------------------
  // THIRD YEAR (TY) - ADVANCED CSE & SPECIALIZATION
  // ----------------------------------------------------
  {
    id: 17,
    title: 'Meta Front-End Developer Professional Certificate',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Front-End',
    provider: 'Meta',
    track: 'Software Development',
    category: 'FullStack',
    rating: 4.7,
    estimatedHours: '140 hrs (9 courses)',
    level: 'Beginner to Advanced',
    whyUseful: 'React, JavaScript, HTML/CSS, Git and front-end development; directly aligned with web roles.',
    courseUrl: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    searchUrl: 'https://www.coursera.org/search?query=Meta%20Front-End%20Developer',
    keySkills: ['React.js', 'Advanced JavaScript', 'UI/UX Design with Figma', 'Jest Testing', 'Capstone Project'],
    badgeColor: '#0668e1',
    isSpecialization: true,
    isShortlist: true,
  },
  {
    id: 18,
    title: 'IBM Full Stack Software Developer Professional Certificate',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Back-End / Full Stack',
    provider: 'IBM',
    track: 'Software Development',
    category: 'FullStack',
    rating: 4.7,
    estimatedHours: '160 hrs (12 courses)',
    level: 'Beginner to Advanced',
    whyUseful: 'Broad full-stack path covering frontend/backend, APIs, databases, containers and cloud-oriented development.',
    courseUrl: 'https://www.coursera.org/professional-certificates/ibm-full-stack-cloud-developer',
    searchUrl: 'https://www.coursera.org/search?query=IBM%20Full%20Stack%20Software%20Developer',
    keySkills: ['Node.js & Express', 'React', 'Python & Django', 'Docker & Kubernetes', 'Microservices & CI/CD'],
    badgeColor: '#6366f1',
    isSpecialization: true,
    isShortlist: true,
  },
  {
    id: 19,
    title: 'Meta Back-End Developer Professional Certificate',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Back-End',
    provider: 'Meta',
    track: 'Software Development',
    category: 'FullStack',
    rating: 4.7,
    estimatedHours: '130 hrs (9 courses)',
    level: 'Intermediate',
    whyUseful: 'Python, Django, APIs, databases, Git and backend development.',
    courseUrl: 'https://www.coursera.org/professional-certificates/meta-back-end-developer',
    searchUrl: 'https://www.coursera.org/search?query=Meta%20Back-End%20Developer',
    keySkills: ['Python & Django', 'REST APIs', 'MySQL / PostgreSQL', 'Django REST Framework', 'API Security'],
    badgeColor: '#0668e1',
    isSpecialization: true,
  },
  {
    id: 20,
    title: 'Meta Database Engineer Professional Certificate',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Database',
    provider: 'Meta',
    track: 'Software Development',
    category: 'CoreCS',
    rating: 4.7,
    estimatedHours: '110 hrs (8 courses)',
    level: 'Intermediate to Advanced',
    whyUseful: 'Database design, SQL and database engineering skills for software/data roles.',
    courseUrl: 'https://www.coursera.org/professional-certificates/meta-database-engineer',
    searchUrl: 'https://www.coursera.org/search?query=Meta%20Database%20Engineer',
    keySkills: ['Advanced SQL', 'Database Normalization', 'MySQL Administration', 'Database Optimization & Indexing'],
    badgeColor: '#0668e1',
    isSpecialization: true,
  },
  {
    id: 21,
    title: 'Machine Learning Specialization',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'AI / ML',
    provider: 'DeepLearning.AI + Stanford Online',
    track: 'AI / Data',
    category: 'AI_ML',
    rating: 4.9,
    estimatedHours: '80 hrs (3 courses)',
    level: 'Beginner to Intermediate',
    whyUseful: 'Core ML: supervised/unsupervised learning, practical model building and evaluation.',
    courseUrl: 'https://www.coursera.org/specializations/machine-learning-introduction',
    searchUrl: 'https://www.coursera.org/search?query=Machine%20Learning%20Specialization%20DeepLearning%20AI%20Stanford',
    keySkills: ['Supervised Learning', 'Linear/Logistic Regression', 'Neural Networks', 'Decision Trees', 'Unsupervised & RL'],
    badgeColor: '#9333ea',
    isSpecialization: true,
    isShortlist: true,
  },
  {
    id: 22,
    title: 'Deep Learning Specialization',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Deep Learning',
    provider: 'DeepLearning.AI',
    track: 'AI / Data',
    category: 'AI_ML',
    rating: 4.9,
    estimatedHours: '90 hrs (5 courses)',
    level: 'Intermediate to Advanced',
    whyUseful: 'Neural networks, CNNs, sequence models and practical deep learning.',
    courseUrl: 'https://www.coursera.org/specializations/deep-learning',
    searchUrl: 'https://www.coursera.org/search?query=Deep%20Learning%20Specialization',
    keySkills: ['CNNs & Computer Vision', 'RNNs & Transformers', 'TensorFlow', 'Hyperparameter Tuning', 'Structuring ML Projects'],
    badgeColor: '#9333ea',
    isSpecialization: true,
  },
  {
    id: 23,
    title: 'IBM Data Science Professional Certificate',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Data Science',
    provider: 'IBM',
    track: 'AI / Data',
    category: 'DataScience',
    rating: 4.6,
    estimatedHours: '140 hrs (10 courses)',
    level: 'Beginner to Intermediate',
    whyUseful: 'Python, SQL, data analysis, visualization and applied data science workflow.',
    courseUrl: 'https://www.coursera.org/professional-certificates/ibm-data-science',
    searchUrl: 'https://www.coursera.org/search?query=IBM%20Data%20Science%20Professional%20Certificate',
    keySkills: ['Data Analysis (Pandas)', 'Data Visualization (Matplotlib/Seaborn)', 'Scikit-Learn ML', 'Applied Data Capstone'],
    badgeColor: '#6366f1',
    isSpecialization: true,
  },
  {
    id: 24,
    title: 'Google Data Analytics Professional Certificate',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Data Analytics',
    provider: 'Google',
    track: 'AI / Data',
    category: 'DataScience',
    rating: 4.8,
    estimatedHours: '180 hrs (8 courses)',
    level: 'Beginner',
    whyUseful: 'Structured analytics path covering spreadsheets, SQL, data cleaning and visualization.',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-data-analytics',
    searchUrl: 'https://www.coursera.org/search?query=Google%20Data%20Analytics%20Professional%20Certificate',
    keySkills: ['Spreadsheets & SQL', 'Tableau Dashboards', 'R Programming', 'Data Cleaning & Transformation'],
    badgeColor: '#10b981',
    isSpecialization: true,
  },
  {
    id: 25,
    title: 'Software Design and Architecture Specialization',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Software Engineering',
    provider: 'University of Alberta',
    track: 'Career / Engineering',
    category: 'CoreCS',
    rating: 4.7,
    estimatedHours: '60 hrs (4 courses)',
    level: 'Intermediate to Advanced',
    whyUseful: 'Software architecture, design principles and maintainable system design.',
    courseUrl: 'https://www.coursera.org/specializations/software-design-architecture',
    searchUrl: 'https://www.coursera.org/search?query=Software%20Design%20and%20Architecture%20Specialization',
    keySkills: ['Design Patterns (GoF)', 'Object-Oriented Design', 'Software Architecture', 'Service-Oriented Architecture (SOA)'],
    badgeColor: '#8b5cf6',
    isSpecialization: true,
    isShortlist: true,
  },
  {
    id: 26,
    title: 'Google Cloud Computing Foundations',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Cloud',
    provider: 'Google Cloud',
    track: 'Cloud / DevOps',
    category: 'Cloud_DevOps',
    rating: 4.7,
    estimatedHours: '40 hrs (4 courses)',
    level: 'Beginner',
    whyUseful: 'Cloud concepts, infrastructure and core cloud technologies.',
    courseUrl: 'https://www.coursera.org/specializations/gcp-cloud-architecture',
    searchUrl: 'https://www.coursera.org/search?query=Google%20Cloud%20Computing%20Foundations',
    keySkills: ['Cloud Infrastructure', 'Compute Engine & GKE', 'Cloud Storage & IAM', 'Networking & BigQuery'],
    badgeColor: '#10b981',
    isSpecialization: true,
    isShortlist: true,
  },
  {
    id: 27,
    title: 'AWS Cloud Technical Essentials',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Cloud',
    provider: 'Amazon Web Services',
    track: 'Cloud / DevOps',
    category: 'Cloud_DevOps',
    rating: 4.7,
    estimatedHours: '16 hrs',
    level: 'Beginner',
    whyUseful: 'AWS fundamentals and cloud architecture concepts for beginners.',
    courseUrl: 'https://www.coursera.org/learn/aws-cloud-technical-essentials',
    searchUrl: 'https://www.coursera.org/search?query=AWS%20Cloud%20Technical%20Essentials',
    keySkills: ['EC2 & S3', 'VPC & Security Groups', 'RDS & DynamoDB', 'IAM Roles & Auto-scaling'],
    badgeColor: '#f97316',
    isSpecialization: false,
    isShortlist: true,
  },
  {
    id: 28,
    title: 'Google Cybersecurity Professional Certificate',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Cybersecurity',
    provider: 'Google',
    track: 'Cybersecurity',
    category: 'CoreCS',
    rating: 4.8,
    estimatedHours: '160 hrs (8 courses)',
    level: 'Beginner to Intermediate',
    whyUseful: 'Security fundamentals, Linux, networks, SIEM and security operations concepts.',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    searchUrl: 'https://www.coursera.org/search?query=Google%20Cybersecurity%20Professional%20Certificate',
    keySkills: ['SIEM (Chronicle/Splunk)', 'Python for Security', 'Linux CLI & SQL', 'Incident Detection & Response', 'NIST Framework'],
    badgeColor: '#10b981',
    isSpecialization: true,
    isShortlist: true,
  },
  {
    id: 29,
    title: 'IBM Cybersecurity Analyst Professional Certificate',
    year: 'TY',
    yearLabel: '3rd Year (TY)',
    subject: 'Cybersecurity',
    provider: 'IBM',
    track: 'Cybersecurity',
    category: 'CoreCS',
    rating: 4.6,
    estimatedHours: '140 hrs (8 courses)',
    level: 'Beginner to Intermediate',
    whyUseful: 'Security analysis, network security, incident response and practical cybersecurity skills.',
    courseUrl: 'https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst',
    searchUrl: 'https://www.coursera.org/search?query=IBM%20Cybersecurity%20Analyst%20Professional%20Certificate',
    keySkills: ['Network Security Analysis', 'Wireshark & Pen-testing', 'Vulnerability Assessment', 'Threat Intelligence'],
    badgeColor: '#6366f1',
    isSpecialization: true,
    isShortlist: true,
  },

  // ----------------------------------------------------
  // FOURTH YEAR (FINAL) - INDUSTRY, DEVOPS & SPECIALIZATION
  // ----------------------------------------------------
  {
    id: 30,
    title: 'DevOps on AWS Specialization',
    year: 'Final',
    yearLabel: '4th Year (Final)',
    subject: 'Cloud / DevOps',
    provider: 'Amazon Web Services',
    track: 'Cloud / DevOps',
    category: 'Cloud_DevOps',
    rating: 4.7,
    estimatedHours: '50 hrs (4 courses)',
    level: 'Intermediate to Advanced',
    whyUseful: 'CI/CD, containers, infrastructure and DevOps practices on AWS.',
    courseUrl: 'https://www.coursera.org/specializations/aws-devops',
    searchUrl: 'https://www.coursera.org/search?query=DevOps%20on%20AWS%20Specialization',
    keySkills: ['AWS CodePipeline', 'AWS CloudFormation (IaC)', 'ECS & EKS Containers', 'Continuous Monitoring & Logging'],
    badgeColor: '#f97316',
    isSpecialization: true,
  },
  {
    id: 31,
    title: 'Google Cloud DevOps Engineer Professional Certificate',
    year: 'Final',
    yearLabel: '4th Year (Final)',
    subject: 'Cloud / DevOps',
    provider: 'Google Cloud',
    track: 'Cloud / DevOps',
    category: 'Cloud_DevOps',
    rating: 4.8,
    estimatedHours: '80 hrs (6 courses)',
    level: 'Advanced',
    whyUseful: 'DevOps, CI/CD, monitoring and cloud-native engineering concepts.',
    courseUrl: 'https://www.coursera.org/professional-certificates/cloud-devops-engineer',
    searchUrl: 'https://www.coursera.org/search?query=Google%20Cloud%20DevOps%20Engineer',
    keySkills: ['GCP Cloud Build', 'SRE Principles', 'Google Kubernetes Engine (GKE)', 'Cloud Monitoring & Prometheus'],
    badgeColor: '#10b981',
    isSpecialization: true,
  },
  {
    id: 32,
    title: 'Software Architecture for Big Data Specialization',
    year: 'Final',
    yearLabel: '4th Year (Final)',
    subject: 'System Design / Architecture',
    provider: 'University of Colorado Boulder',
    track: 'Career / Engineering',
    category: 'CoreCS',
    rating: 4.6,
    estimatedHours: '50 hrs (4 courses)',
    level: 'Advanced',
    whyUseful: 'Architecture concepts relevant to scalable/data-intensive systems.',
    courseUrl: 'https://www.coursera.org/specializations/software-architecture-big-data',
    searchUrl: 'https://www.coursera.org/search?query=Software%20Architecture%20for%20Big%20Data',
    keySkills: ['Distributed Systems', 'CAP Theorem', 'Event-Driven Architectures', 'Kafka & Spark Integration'],
    badgeColor: '#8b5cf6',
    isSpecialization: true,
  },
  {
    id: 33,
    title: 'Agile Development Specialization',
    year: 'Final',
    yearLabel: '4th Year (Final)',
    subject: 'Project / Agile',
    provider: 'University of Virginia',
    track: 'Career / Engineering',
    category: 'CoreCS',
    rating: 4.7,
    estimatedHours: '40 hrs (4 courses)',
    level: 'Intermediate',
    whyUseful: 'Agile development, product/project practices and team delivery.',
    courseUrl: 'https://www.coursera.org/specializations/agile-development',
    searchUrl: 'https://www.coursera.org/search?query=Agile%20Development%20Specialization',
    keySkills: ['Scrum & Kanban', 'User Stories & Epics', 'Sprint Planning', 'Continuous Delivery Mindset'],
    badgeColor: '#0ea5e9',
    isSpecialization: true,
  },
  {
    id: 34,
    title: 'Generative AI with Large Language Models',
    year: 'Final',
    yearLabel: '4th Year (Final)',
    subject: 'AI / Advanced',
    provider: 'DeepLearning.AI + AWS',
    track: 'AI / Data',
    category: 'AI_ML',
    rating: 4.8,
    estimatedHours: '16 hrs',
    level: 'Intermediate to Advanced',
    whyUseful: 'Modern GenAI/LLM concepts, model lifecycle and application-oriented understanding.',
    courseUrl: 'https://www.coursera.org/learn/generative-ai-with-llms',
    searchUrl: 'https://www.coursera.org/search?query=Generative%20AI%20with%20Large%20Language%20Models',
    keySkills: ['Transformer Architectures', 'Fine-Tuning (PEFT / LoRA)', 'RLHF', 'RAG & Vector Databases', 'LLM Deployment'],
    badgeColor: '#9333ea',
    isSpecialization: false,
  },
  {
    id: 35,
    title: 'Google IT Support Professional Certificate',
    year: 'Final',
    yearLabel: '4th Year (Final)',
    subject: 'Interview / Career',
    provider: 'Google',
    track: 'Career / Engineering',
    category: 'CoreCS',
    rating: 4.8,
    estimatedHours: '150 hrs (5 courses)',
    level: 'Beginner to Intermediate',
    whyUseful: 'Broader IT troubleshooting/networking/system support foundation; useful as an optional support-level credential.',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-it-support',
    searchUrl: 'https://www.coursera.org/search?query=Google%20IT%20Support%20Professional%20Certificate',
    keySkills: ['Hardware Troubleshooting', 'Customer Support', 'Networking Basics', 'System Administration'],
    badgeColor: '#10b981',
    isSpecialization: true,
  },
];

export const RESUME_SHORTLIST = [
  {
    rank: 1,
    course: 'Algorithms, Part I + II',
    provider: 'Princeton University',
    skill: 'DSA / interview foundation',
    resumePurpose: 'Strong academic core for product company coding rounds',
    courseUrl: 'https://www.coursera.org/learn/algorithms-part1',
    tag: 'Academic Core',
  },
  {
    rank: 2,
    course: 'Object Oriented Programming in Java Specialization',
    provider: 'Duke University',
    skill: 'OOP / Java',
    resumePurpose: 'Core software development and clean object-oriented architecture',
    courseUrl: 'https://www.coursera.org/specializations/object-oriented-programming',
    tag: 'Core Software',
  },
  {
    rank: 3,
    course: 'Meta Front-End Developer OR IBM Full Stack Software Developer',
    provider: 'Meta / IBM',
    skill: 'Web / Full Stack',
    resumePurpose: 'Choose based on your development path (React or full-stack cloud)',
    courseUrl: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    tag: 'Web & Full Stack',
  },
  {
    rank: 4,
    course: 'Machine Learning Specialization',
    provider: 'DeepLearning.AI + Stanford Online',
    skill: 'AI/ML',
    resumePurpose: 'Industry standard foundational AI/ML credential by Andrew Ng',
    courseUrl: 'https://www.coursera.org/specializations/machine-learning-introduction',
    tag: 'AI / ML Core',
  },
  {
    rank: 5,
    course: 'Google Cybersecurity OR IBM Cybersecurity Analyst',
    provider: 'Google / IBM',
    skill: 'Cybersecurity',
    resumePurpose: 'Demonstrates security operations, SIEM tools, and SOC defense workflows',
    courseUrl: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    tag: 'Security Track',
  },
  {
    rank: 6,
    course: 'Google Cloud / AWS Cloud Course',
    provider: 'Google Cloud / AWS',
    skill: 'Cloud Computing',
    resumePurpose: 'High impact for cloud-native deployment and modern infrastructure',
    courseUrl: 'https://www.coursera.org/specializations/gcp-cloud-architecture',
    tag: 'Cloud & Scale',
  },
  {
    rank: 7,
    course: 'Software Design and Architecture Specialization',
    provider: 'University of Alberta',
    skill: 'Architecture & System Design',
    resumePurpose: 'Demonstrates software engineering maturity for final-year & SDE-1 roles',
    courseUrl: 'https://www.coursera.org/specializations/software-design-architecture',
    tag: 'System Design',
  },
];

export const ROLE_BASED_PATHS = [
  {
    role: 'Full-Stack Developer',
    icon: 'Globe',
    accentColor: '#3b82f6',
    description: 'Build interactive frontends, scalable REST/GraphQL APIs, and enterprise database systems.',
    steps: [
      { name: 'Git & GitHub Workflow', provider: 'IBM / Atlassian', year: 'FY-SY' },
      { name: 'Meta Front-End Developer', provider: 'Meta', year: 'TY' },
      { name: 'IBM Full Stack or Meta Back-End', provider: 'IBM / Meta', year: 'TY' },
      { name: 'Meta Database Engineer (SQL/DB)', provider: 'Meta', year: 'TY' },
      { name: 'Software Design & Architecture', provider: 'Univ of Alberta', year: 'TY-Final' },
      { name: 'AWS / GCP Cloud Deployment', provider: 'AWS / Google', year: 'Final' },
    ],
  },
  {
    role: 'AI / ML Engineer',
    icon: 'Brain',
    accentColor: '#8b5cf6',
    description: 'Design machine learning pipelines, deep neural networks, and deploy Generative AI applications.',
    steps: [
      { name: 'Python Programming', provider: 'Google / UMich', year: 'FY' },
      { name: 'Mathematics for ML (LinAlg + Calc)', provider: 'Imperial College', year: 'FY' },
      { name: 'Machine Learning Specialization', provider: 'DeepLearning.AI + Stanford', year: 'TY' },
      { name: 'Deep Learning Specialization', provider: 'DeepLearning.AI', year: 'TY' },
      { name: 'Generative AI with LLMs', provider: 'DeepLearning.AI + AWS', year: 'Final' },
      { name: 'Cloud-Deployed ML Model System', provider: 'AWS / GCP', year: 'Final' },
    ],
  },
  {
    role: 'Cybersecurity Specialist',
    icon: 'Shield',
    accentColor: '#10b981',
    description: 'Protect networks, audit web apps, analyze SIEM threat logs, and respond to incidents.',
    steps: [
      { name: 'Computer Networking (Bits & Bytes)', provider: 'Google', year: 'FY' },
      { name: 'Operating Systems & Linux Power User', provider: 'Google', year: 'FY-SY' },
      { name: 'Google Cybersecurity Professional Cert', provider: 'Google', year: 'TY' },
      { name: 'IBM Cybersecurity Analyst', provider: 'IBM', year: 'TY' },
      { name: 'Web Security & Pen-Testing Labs', provider: 'Practicals / PortSwigger', year: 'Final' },
      { name: 'Cloud Security & Compliance', provider: 'AWS / Google Cloud', year: 'Final' },
    ],
  },
  {
    role: 'Data Scientist / Analyst',
    icon: 'Database',
    accentColor: '#ec4899',
    description: 'Transform raw data into predictive insights, BI dashboards, and statistical models.',
    steps: [
      { name: 'Python for Everybody', provider: 'University of Michigan', year: 'FY' },
      { name: 'Databases & SQL for Data Science', provider: 'IBM', year: 'SY' },
      { name: 'Google Data Analytics Professional Cert', provider: 'Google', year: 'TY' },
      { name: 'IBM Data Science Professional Cert', provider: 'IBM', year: 'TY' },
      { name: 'Machine Learning Specialization', provider: 'DeepLearning.AI', year: 'TY-Final' },
      { name: 'Portfolio Data Science Capstone', provider: 'Deployed Project', year: 'Final' },
    ],
  },
  {
    role: 'Cloud & DevOps Engineer',
    icon: 'Server',
    accentColor: '#f97316',
    description: 'Automate CI/CD pipelines, containerize microservices with Kubernetes, and orchestrate cloud infrastructure.',
    steps: [
      { name: 'Linux Power User & OS Internals', provider: 'Google', year: 'FY' },
      { name: 'Version Control with Git', provider: 'Atlassian / IBM', year: 'SY' },
      { name: 'AWS Cloud Essentials / GCP Foundations', provider: 'AWS / Google', year: 'TY' },
      { name: 'Docker & Kubernetes Containers', provider: 'IBM Cloud Dev', year: 'TY' },
      { name: 'DevOps on AWS / GCP DevOps Engineer', provider: 'AWS / Google Cloud', year: 'Final' },
      { name: 'Production Deployed Cloud-Native System', provider: 'Capstone Project', year: 'Final' },
    ],
  },
];

export const RESUME_BEST_PRACTICES = [
  {
    title: 'Exact Credential Naming',
    desc: 'Write the exact certificate name, provider institution (e.g. Stanford / Meta / Google), completion date, and clickable Coursera credential verification link.',
  },
  {
    title: 'Dedicated Certifications Section',
    desc: 'Put certificates under a dedicated Certifications section on your resume; showcase 2 to 4 high-value credentials matching your target job role.',
  },
  {
    title: 'Pair Every Certificate with a GitHub Project',
    desc: 'For every major certificate, add a related GitHub project or live deployed URL in your Projects section to prove real-world implementation.',
  },
  {
    title: 'Be Prepared for Technical Interview Defense',
    desc: 'During interviews, be ready to explain the architecture, assignments, trade-offs, and technical concepts learned in the certification.',
  },
  {
    title: 'Avoid Credential Fluff (Quality > Quantity)',
    desc: 'Avoid listing 20–30 beginner badges. A focused stack of 2–4 rigorous professional certificates aligned with your target role is much easier to defend.',
  },
];
