const booksSeedData = [
  {
    title: 'Introduction to Algorithms (CLRS)',
    authors: ['Thomas H. Cormen', 'Charles E. Leiserson', 'Ronald L. Rivest', 'Clifford Stein'],
    category: 'DSA',
    level: 'Intermediate',
    description: 'The definitive international standard algorithms reference covering asymptotic analysis, dynamic programming, greedy algorithms, graph algorithms, and NP-completeness.',
    publisher: 'MIT Press',
    edition: '4th Edition',
    officialUrl: 'https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/',
    libraryUrl: 'https://openlibrary.org/works/OL27471W/Introduction_to_Algorithms',
    tags: ['Algorithms', 'Data Structures', 'MIT', 'Reference', 'CLRS'],
    isStandardTextbook: true,
  },
  {
    title: 'Database System Concepts',
    authors: ['Abraham Silberschatz', 'Henry F. Korth', 'S. Sudarshan'],
    category: 'DBMS',
    level: 'Beginner',
    description: 'The globally adopted textbook for database architecture, relational algebra, SQL optimization, transaction management, concurrency control, and indexing.',
    publisher: 'McGraw-Hill Higher Education',
    edition: '7th Edition',
    officialUrl: 'https://www.db-book.com/',
    libraryUrl: 'https://openlibrary.org/works/OL1816301W/Database_System_Concepts',
    tags: ['DBMS', 'SQL', 'Transactions', 'ACID', 'Indexing'],
    isStandardTextbook: true,
  },
  {
    title: 'Operating System Concepts (The Dinosaur Book)',
    authors: ['Abraham Silberschatz', 'Peter B. Galvin', 'Greg Gagne'],
    category: 'Operating Systems',
    level: 'Beginner',
    description: 'Core standard text covering process synchronization, threads, CPU scheduling, deadlocks, memory management, virtual memory, and file systems.',
    publisher: 'Wiley',
    edition: '10th Edition',
    officialUrl: 'https://www.os-book.com/OS10/',
    libraryUrl: 'https://openlibrary.org/works/OL1957242W/Operating_System_Concepts',
    tags: ['Operating Systems', 'Processes', 'Threads', 'Virtual Memory', 'Kernel'],
    isStandardTextbook: true,
  },
  {
    title: 'Computer Networking: A Top-Down Approach',
    authors: ['James F. Kurose', 'Keith W. Ross'],
    category: 'Computer Networks',
    level: 'Beginner',
    description: 'Teaches networking by starting from the Application Layer (HTTP, DNS, WebSockets) and moving down through Transport (TCP/UDP), Network (IP, Routing), and Link layers.',
    publisher: 'Pearson',
    edition: '8th Edition',
    officialUrl: 'https://www.pearson.com/en-us/subject-catalog/p/computer-networking-a-top-down-approach/P200000003310',
    libraryUrl: 'https://openlibrary.org/works/OL27289W/Computer_Networking',
    tags: ['Networking', 'TCP/IP', 'HTTP', 'DNS', 'Kurose Ross'],
    isStandardTextbook: true,
  },
  {
    title: 'Designing Data-Intensive Applications (DDIA)',
    authors: ['Martin Kleppmann'],
    category: 'System Design',
    level: 'Advanced',
    description: 'The modern industry gold standard for distributed systems engineering, covering replication, partitioning, transactions, consensus (Raft/Paxos), and stream processing.',
    publisher: "O'Reilly Media",
    edition: '1st Edition',
    officialUrl: 'https://dataintensive.net/',
    libraryUrl: 'https://openlibrary.org/works/OL17845781W/Designing_Data-Intensive_Applications',
    tags: ['System Design', 'Distributed Systems', 'Replication', 'Sharding', 'Kafka'],
    isStandardTextbook: false,
  },
  {
    title: 'Computer Systems: A Programmer’s Perspective (CS:APP)',
    authors: ['Randal E. Bryant', 'David R. O’Hallaron'],
    category: 'Distributed Systems',
    level: 'Intermediate',
    description: 'Explains how computer hardware executes code, machine-level representations, processor architecture, cache memories, and linking.',
    publisher: 'Pearson',
    edition: '3rd Edition',
    officialUrl: 'http://csapp.cs.cmu.edu/',
    libraryUrl: 'https://openlibrary.org/works/OL28117W/Computer_Systems',
    tags: ['Systems', 'Computer Architecture', 'Assembly', 'Cache Memory', 'CMU'],
    isStandardTextbook: true,
  },
  {
    title: 'Deep Learning',
    authors: ['Ian Goodfellow', 'Yoshua Bengio', 'Aaron Courville'],
    category: 'AI',
    level: 'Advanced',
    description: 'MIT Press textbook covering applied math and machine learning basics, deep feedforward networks, regularization, convolutional networks, and generative models.',
    publisher: 'MIT Press',
    edition: '1st Edition',
    officialUrl: 'https://www.deeplearningbook.org/',
    libraryUrl: 'https://openlibrary.org/works/OL17355152W/Deep_Learning',
    tags: ['Deep Learning', 'Neural Networks', 'AI', 'PyTorch', 'Math'],
    isStandardTextbook: true,
  },
];

module.exports = booksSeedData;
