const coursesSeedData = [
  {
    title: 'Google IT Automation with Python Professional Certificate',
    provider: 'Coursera',
    instructor: 'Google Career Certificates',
    institution: 'Google',
    category: 'CoreCS',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/professional-certificates/google-it-automation',
    description: 'Strong beginner-to-intermediate Python + automation + Git/GitHub/Linux foundation. Learn to automate tasks with Python scripts, use Git and GitHub for version control, and manage system resources.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 120,
    rating: 4.8,
    skillsTaught: ['Python Programming', 'Git & GitHub', 'Linux CLI', 'IT Automation', 'Troubleshooting'],
    tags: ['FY', 'Python', 'Google', 'Automation', 'Git', 'Linux'],
    isPublished: true,
  },
  {
    title: 'Programming for Everybody (Getting Started with Python)',
    provider: 'Coursera',
    instructor: 'Charles Severance',
    institution: 'University of Michigan',
    category: 'CoreCS',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/learn/python',
    description: 'Beginner-friendly Python foundation; useful if Python is new. Covers variables, expressions, conditional code, functions, and loops.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 19,
    rating: 4.8,
    skillsTaught: ['Python Syntax', 'Variables & Expressions', 'Conditional Execution', 'Functions & Loops'],
    tags: ['FY', 'Python', 'University of Michigan', 'Programming Basics'],
    isPublished: true,
  },
  {
    title: 'HTML, CSS, and Javascript for Web Developers',
    provider: 'Coursera',
    instructor: 'Yaakov Chaikin',
    institution: 'Johns Hopkins University',
    category: 'FullStack',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/learn/html-css-javascript-for-web-developers',
    description: 'Builds core web fundamentals before frameworks. Learn modern web development tools and practices, responsive web design with CSS/Flexbox, and JavaScript interaction.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 40,
    rating: 4.7,
    skillsTaught: ['HTML5', 'CSS3 Layouts', 'Responsive Web Design', 'JavaScript DOM', 'Ajax'],
    tags: ['FY', 'Web Development', 'HTML', 'CSS', 'JavaScript'],
    isPublished: true,
  },
  {
    title: 'Introduction to Git and GitHub',
    provider: 'Coursera',
    instructor: 'IBM Skills Network',
    institution: 'IBM',
    category: 'CoreCS',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/learn/introduction-git-github',
    description: 'Practical Git/GitHub workflow for repositories and collaboration. Master commits, branches, pull requests, merges, and remote team workflows.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 12,
    rating: 4.7,
    skillsTaught: ['Git Version Control', 'GitHub Repositories', 'Branching & Merging', 'Pull Requests'],
    tags: ['FY', 'Git', 'GitHub', 'IBM', 'Collaboration'],
    isPublished: true,
  },
  {
    title: 'The Bits and Bytes of Computer Networking',
    provider: 'Coursera',
    instructor: 'Google Career Certificates',
    institution: 'Google',
    category: 'CoreCS',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/learn/computer-networking',
    description: 'Good introduction to networking concepts before deeper CN study. Covers TCP/IP, IP addressing, subnetting, DNS, routing, and network troubleshooting.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 34,
    rating: 4.8,
    skillsTaught: ['TCP/IP Protocol Suite', 'DNS & DHCP', 'Subnetting & Routing', 'Network Layers', 'Troubleshooting'],
    tags: ['FY', 'Networking', 'Google', 'Computer Networks', 'TCP/IP'],
    isPublished: true,
  },
  {
    title: 'Operating Systems and You: Becoming a Power User',
    provider: 'Coursera',
    instructor: 'Google Career Certificates',
    institution: 'Google',
    category: 'CoreCS',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/learn/os-power-user',
    description: 'Introduces OS concepts, processes, memory, files and command-line skills across Windows and Linux environments.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 35,
    rating: 4.7,
    skillsTaught: ['Linux Command Line', 'Process Management', 'File Systems & Storage', 'PowerShell', 'Operating Systems'],
    tags: ['FY', 'OS', 'Linux', 'Google', 'Operating Systems'],
    isPublished: true,
  },
  {
    title: 'Mathematics for Machine Learning: Linear Algebra',
    provider: 'Coursera',
    instructor: 'David Dye',
    institution: 'Imperial College London',
    category: 'AI_ML',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/learn/linear-algebra-machine-learning',
    description: 'Useful mathematical foundation for later ML/AI study. Master vector spaces, matrices, eigenvalues, eigenvectors, and geometric transformations.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 19,
    rating: 4.7,
    skillsTaught: ['Vectors & Matrices', 'Linear Transformations', 'Eigenvalues & Eigenvectors', 'PageRank Algorithm'],
    tags: ['FY', 'Mathematics', 'Linear Algebra', 'Imperial College', 'AI_ML'],
    isPublished: true,
  },
  {
    title: 'Mathematics for Machine Learning: Multivariate Calculus',
    provider: 'Coursera',
    instructor: 'Sam Cooper',
    institution: 'Imperial College London',
    category: 'AI_ML',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/learn/multivariate-calculus-machine-learning',
    description: 'Calculus concepts useful for ML foundations. Covers gradients, Jacobian/Hessian matrices, multivariate Taylor series, and neural network gradient descent.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 18,
    rating: 4.7,
    skillsTaught: ['Multivariate Calculus', 'Gradients & Optimization', 'Jacobian Matrix', 'Backpropagation Math'],
    tags: ['FY', 'Mathematics', 'Calculus', 'Imperial College', 'Optimization'],
    isPublished: true,
  },
  {
    title: 'Algorithms, Part I',
    provider: 'Coursera',
    instructor: 'Robert Sedgewick & Kevin Wayne',
    institution: 'Princeton University',
    category: 'Algorithms',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/learn/algorithms-part1',
    description: 'University-level algorithms and data structures foundation; strong for DSA depth. Covers union-find, stacks, queues, sorting algorithms, priority queues, and BSTs.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 54,
    rating: 4.9,
    skillsTaught: ['Union-Find', 'Sorting Algorithms', 'Binary Search Trees', 'Priority Queues', 'Time & Space Complexity'],
    tags: ['SY', 'DSA', 'Algorithms', 'Princeton', 'Interview Prep'],
    isPublished: true,
  },
  {
    title: 'Algorithms, Part II',
    provider: 'Coursera',
    instructor: 'Robert Sedgewick & Kevin Wayne',
    institution: 'Princeton University',
    category: 'Algorithms',
    difficulty: 'Advanced',
    url: 'https://www.coursera.org/learn/algorithms-part2',
    description: 'Advanced graph and algorithm topics following Part I. Covers graph algorithms, minimum spanning trees, shortest paths, max-flow, string sorts, and data compression.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 58,
    rating: 4.9,
    skillsTaught: ['Graph Algorithms', 'Dijkstra & Shortest Paths', 'Max Flow / Min Cut', 'Tries & String Sorts', 'Data Compression'],
    tags: ['SY', 'DSA', 'Graph Algorithms', 'Princeton', 'Advanced Algorithms'],
    isPublished: true,
  },
  {
    title: 'Object Oriented Programming in Java Specialization',
    provider: 'Coursera',
    instructor: 'Duke University Faculty',
    institution: 'Duke University',
    category: 'FullStack',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/specializations/object-oriented-programming',
    description: 'Java + OOP + software design through a multi-course specialization. Build clean class hierarchies, utilize polymorphism, implement data structures, and create interactive graphical programs.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 80,
    rating: 4.7,
    skillsTaught: ['Java Programming', 'OOP Design Principles', 'Inheritance & Polymorphism', 'Data Structures in Java', 'GUI Development'],
    tags: ['SY', 'Java', 'OOP', 'Duke University', 'Software Design'],
    isPublished: true,
  },
  {
    title: 'Introduction to Relational Databases',
    provider: 'Coursera',
    instructor: 'IBM Skills Network',
    institution: 'IBM',
    category: 'CoreCS',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/learn/introduction-to-relational-databases',
    description: 'Relational database concepts and SQL foundation. Learn relational models, tables, keys, entity relationships, and core SQL querying syntax.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 15,
    rating: 4.6,
    skillsTaught: ['Relational Database Concepts', 'SQL DDL & DML', 'Primary & Foreign Keys', 'ER Modeling'],
    tags: ['SY', 'DBMS', 'SQL', 'IBM', 'Databases'],
    isPublished: true,
  },
  {
    title: 'Databases and SQL for Data Science with Python',
    provider: 'Coursera',
    instructor: 'IBM Skills Network',
    institution: 'IBM',
    category: 'DataScience',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/learn/sql-data-science',
    description: 'Practical SQL plus Python/data workflow; useful beyond academic DBMS. Learn database access with Python, writing complex joins, aggregates, and stored procedures.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 38,
    rating: 4.7,
    skillsTaught: ['SQL Joins & Aggregates', 'Python DB-API', 'Pandas SQL Queries', 'Stored Procedures & Views'],
    tags: ['SY', 'SQL', 'Python', 'IBM', 'Data Science'],
    isPublished: true,
  },
  {
    title: 'Computer Communications Specialization',
    provider: 'Coursera',
    instructor: 'University of Colorado Boulder Faculty',
    institution: 'University of Colorado System',
    category: 'CoreCS',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/specializations/computer-communications',
    description: 'Deeper networking concepts and practical communication systems. Master packet switching, routing algorithms, transport layer protocols, and wireless networking.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 50,
    rating: 4.6,
    skillsTaught: ['Packet Switching', 'TCP Congestion Control', 'Routing Protocols', 'Network Security', 'Socket Programming'],
    tags: ['SY', 'Computer Networks', 'University of Colorado', 'Protocols'],
    isPublished: true,
  },
  {
    title: 'Version Control with Git',
    provider: 'Coursera',
    instructor: 'Atlassian',
    institution: 'Atlassian',
    category: 'FullStack',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/learn/version-control-with-git',
    description: 'Version control practices relevant to team software development. Master branch strategies, Git rebase, resolving conflicts, tagging, and pull request workflows.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 15,
    rating: 4.7,
    skillsTaught: ['Advanced Git Workflows', 'Rebase vs Merge', 'Conflict Resolution', 'Team Collaboration'],
    tags: ['SY', 'Git', 'Atlassian', 'Software Engineering'],
    isPublished: true,
  },
  {
    title: 'Meta Front-End Developer Professional Certificate',
    provider: 'Coursera',
    instructor: 'Meta Engineers',
    institution: 'Meta',
    category: 'FullStack',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    description: 'React, JavaScript, HTML/CSS, Git and front-end development; directly aligned with web roles. Complete 9 courses culminating in a capstone portfolio web application.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 140,
    rating: 4.7,
    skillsTaught: ['React.js', 'Advanced JavaScript', 'HTML5 & CSS3', 'UI/UX with Figma', 'Jest Unit Testing', 'REST APIs'],
    tags: ['TY', 'Front-End', 'React', 'Meta', 'Web Development'],
    isPublished: true,
  },
  {
    title: 'IBM Full Stack Software Developer Professional Certificate',
    provider: 'Coursera',
    instructor: 'IBM Cloud Training',
    institution: 'IBM',
    category: 'FullStack',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/professional-certificates/ibm-full-stack-cloud-developer',
    description: 'Broad full-stack path covering frontend/backend, APIs, databases, containers and cloud-oriented development using Node.js, Python, React, Docker, and Kubernetes.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 160,
    rating: 4.7,
    skillsTaught: ['Node.js & Express', 'React', 'Python & Django', 'Docker & Kubernetes', 'Microservices', 'CI/CD Pipelines'],
    tags: ['TY', 'Full Stack', 'IBM', 'Cloud Development', 'Containers'],
    isPublished: true,
  },
  {
    title: 'Meta Back-End Developer Professional Certificate',
    provider: 'Coursera',
    instructor: 'Meta Engineers',
    institution: 'Meta',
    category: 'FullStack',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/professional-certificates/meta-back-end-developer',
    description: 'Python, Django, APIs, databases, Git and backend development. Build RESTful APIs, manage databases with SQL, and implement secure user authentication.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 130,
    rating: 4.7,
    skillsTaught: ['Python Programming', 'Django Web Framework', 'REST APIs & Endpoints', 'MySQL & PostgreSQL', 'API Security'],
    tags: ['TY', 'Back-End', 'Python', 'Django', 'Meta', 'APIs'],
    isPublished: true,
  },
  {
    title: 'Meta Database Engineer Professional Certificate',
    provider: 'Coursera',
    instructor: 'Meta Engineers',
    institution: 'Meta',
    category: 'CoreCS',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/professional-certificates/meta-database-engineer',
    description: 'Database design, SQL and database engineering skills for software/data roles. Covers normalization, indexing, transactions, stored procedures, and MySQL administration.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 110,
    rating: 4.7,
    skillsTaught: ['Advanced SQL Queries', 'Database Normalization', 'Index Optimization', 'MySQL Database Administration'],
    tags: ['TY', 'Databases', 'SQL', 'Meta', 'Database Engineering'],
    isPublished: true,
  },
  {
    title: 'Machine Learning Specialization',
    provider: 'Coursera',
    instructor: 'Andrew Ng',
    institution: 'DeepLearning.AI',
    category: 'AI_ML',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/specializations/machine-learning-introduction',
    description: 'Core ML: supervised/unsupervised learning, practical model building and evaluation created by Andrew Ng in collaboration with Stanford Online.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 80,
    rating: 4.9,
    skillsTaught: ['Supervised Learning', 'Linear & Logistic Regression', 'Neural Networks', 'Decision Trees', 'Unsupervised Learning', 'Recommender Systems'],
    tags: ['TY', 'AI_ML', 'Machine Learning', 'Andrew Ng', 'Stanford'],
    isPublished: true,
  },
  {
    title: 'Deep Learning Specialization',
    provider: 'Coursera',
    instructor: 'Andrew Ng',
    institution: 'DeepLearning.AI',
    category: 'AI_ML',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/specializations/deep-learning',
    description: 'Neural networks, CNNs, sequence models and practical deep learning. Build computer vision models, NLP Transformer architectures, and hyperparameter tuning pipelines.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 90,
    rating: 4.9,
    skillsTaught: ['Deep Neural Networks', 'Convolutional Networks (CNN)', 'Sequence Models (RNN/LSTM)', 'Transformers', 'TensorFlow'],
    tags: ['TY', 'Deep Learning', 'AI_ML', 'Computer Vision', 'NLP', 'Andrew Ng'],
    isPublished: true,
  },
  {
    title: 'IBM Data Science Professional Certificate',
    provider: 'Coursera',
    instructor: 'IBM Data Scientists',
    institution: 'IBM',
    category: 'DataScience',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/professional-certificates/ibm-data-science',
    description: 'Python, SQL, data analysis, visualization and applied data science workflow. 10 courses covering Pandas, Matplotlib, Scikit-Learn, and real-world predictive modeling.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 140,
    rating: 4.6,
    skillsTaught: ['Python Data Analysis', 'Pandas & NumPy', 'Data Visualization', 'Machine Learning Models', 'Data Science Capstone'],
    tags: ['TY', 'Data Science', 'Python', 'IBM', 'Analytics'],
    isPublished: true,
  },
  {
    title: 'Google Data Analytics Professional Certificate',
    provider: 'Coursera',
    instructor: 'Google Career Certificates',
    institution: 'Google',
    category: 'DataScience',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/professional-certificates/google-data-analytics',
    description: 'Structured analytics path covering spreadsheets, SQL, data cleaning, Tableau visualization, and R programming for business intelligence.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 180,
    rating: 4.8,
    skillsTaught: ['Spreadsheet Analysis', 'SQL Queries & Joins', 'Tableau Dashboards', 'R Programming', 'Data Cleaning'],
    tags: ['TY', 'Data Analytics', 'Google', 'Tableau', 'SQL'],
    isPublished: true,
  },
  {
    title: 'Software Design and Architecture Specialization',
    provider: 'Coursera',
    instructor: 'Kenny Wong',
    institution: 'University of Alberta',
    category: 'CoreCS',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/specializations/software-design-architecture',
    description: 'Software architecture, design principles and maintainable system design. Covers Gang of Four design patterns, object-oriented design, architectural styles, and SOA.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 60,
    rating: 4.7,
    skillsTaught: ['Design Patterns (GoF)', 'Object-Oriented Architecture', 'Software Design Principles', 'Service-Oriented Architecture'],
    tags: ['TY', 'Software Engineering', 'Design Patterns', 'System Design', 'University of Alberta'],
    isPublished: true,
  },
  {
    title: 'Google Cloud Computing Foundations',
    provider: 'Coursera',
    instructor: 'Google Cloud Training',
    institution: 'Google Cloud',
    category: 'Cloud_DevOps',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/specializations/gcp-cloud-architecture',
    description: 'Cloud concepts, infrastructure and core cloud technologies. Master Compute Engine, GKE, Cloud Storage, BigQuery, and IAM on Google Cloud Platform.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 40,
    rating: 4.7,
    skillsTaught: ['Google Cloud Platform', 'Compute Engine', 'Google Kubernetes Engine (GKE)', 'Cloud Storage & IAM', 'BigQuery'],
    tags: ['TY', 'Cloud', 'Google Cloud', 'GCP', 'DevOps'],
    isPublished: true,
  },
  {
    title: 'AWS Cloud Technical Essentials',
    provider: 'Coursera',
    instructor: 'AWS Training & Certification',
    institution: 'Amazon Web Services',
    category: 'Cloud_DevOps',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/learn/aws-cloud-technical-essentials',
    description: 'AWS fundamentals and cloud architecture concepts for beginners. Learn compute (EC2), storage (S3), database (RDS/DynamoDB), and networking (VPC).',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 16,
    rating: 4.7,
    skillsTaught: ['Amazon EC2 & S3', 'Amazon RDS & DynamoDB', 'Amazon VPC', 'AWS IAM Security', 'Cloud Architecture'],
    tags: ['TY', 'AWS', 'Cloud', 'Amazon', 'Cloud Computing'],
    isPublished: true,
  },
  {
    title: 'Google Cybersecurity Professional Certificate',
    provider: 'Coursera',
    instructor: 'Google Career Certificates',
    institution: 'Google',
    category: 'Cybersecurity',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/professional-certificates/google-cybersecurity',
    description: 'Security fundamentals, Linux, networks, SIEM and security operations concepts. Prepare for SOC analyst roles with hands-on SIEM, Python, and incident response labs.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 160,
    rating: 4.8,
    skillsTaught: ['SIEM Tools (Splunk/Chronicle)', 'Python for Security', 'Linux & SQL for Auditing', 'Network Security', 'Incident Response'],
    tags: ['TY', 'Cybersecurity', 'Google', 'Security Operations', 'SIEM'],
    isPublished: true,
  },
  {
    title: 'IBM Cybersecurity Analyst Professional Certificate',
    provider: 'Coursera',
    instructor: 'IBM Security Experts',
    institution: 'IBM',
    category: 'Cybersecurity',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst',
    description: 'Security analysis, network security, incident response and practical cybersecurity skills. Learn vulnerability assessment, pen-testing fundamentals, and compliance.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 140,
    rating: 4.6,
    skillsTaught: ['Cybersecurity Threat Intelligence', 'Network Analysis & Wireshark', 'Incident Response Plan', 'Vulnerability Assessment'],
    tags: ['TY', 'Cybersecurity', 'IBM', 'Penetration Testing', 'Threat Analysis'],
    isPublished: true,
  },
  {
    title: 'DevOps on AWS Specialization',
    provider: 'Coursera',
    instructor: 'AWS Training & Certification',
    institution: 'Amazon Web Services',
    category: 'Cloud_DevOps',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/specializations/aws-devops',
    description: 'CI/CD, containers, infrastructure and DevOps practices on AWS. Learn AWS CodePipeline, CloudFormation Infrastructure as Code, and ECS/EKS container deployments.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 50,
    rating: 4.7,
    skillsTaught: ['AWS CodePipeline & CodeBuild', 'Infrastructure as Code (CloudFormation)', 'ECS & EKS Container Orchestration', 'Continuous Monitoring'],
    tags: ['Final', 'DevOps', 'AWS', 'CI/CD', 'Containers', 'Infrastructure'],
    isPublished: true,
  },
  {
    title: 'Google Cloud DevOps Engineer Professional Certificate',
    provider: 'Coursera',
    instructor: 'Google Cloud Training',
    institution: 'Google Cloud',
    category: 'Cloud_DevOps',
    difficulty: 'Advanced',
    url: 'https://www.coursera.org/professional-certificates/cloud-devops-engineer',
    description: 'DevOps, CI/CD, monitoring and cloud-native engineering concepts. Master Site Reliability Engineering (SRE) principles, Cloud Build, and Kubernetes management.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 80,
    rating: 4.8,
    skillsTaught: ['Site Reliability Engineering (SRE)', 'Google Kubernetes Engine (GKE)', 'Cloud Build CI/CD', 'Monitoring & Prometheus'],
    tags: ['Final', 'DevOps', 'Google Cloud', 'GCP', 'SRE', 'Kubernetes'],
    isPublished: true,
  },
  {
    title: 'Software Architecture for Big Data Specialization',
    provider: 'Coursera',
    instructor: 'University of Colorado Boulder Faculty',
    institution: 'University of Colorado System',
    category: 'CoreCS',
    difficulty: 'Advanced',
    url: 'https://www.coursera.org/specializations/software-architecture-big-data',
    description: 'Architecture concepts relevant to scalable/data-intensive systems. Covers CAP theorem, distributed storage, streaming architectures, and big data scalability.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 50,
    rating: 4.6,
    skillsTaught: ['Distributed Systems Architecture', 'CAP Theorem & Eventual Consistency', 'Big Data Streaming', 'Scalable Cloud Design'],
    tags: ['Final', 'System Design', 'Big Data', 'Distributed Systems', 'Architecture'],
    isPublished: true,
  },
  {
    title: 'Agile Development Specialization',
    provider: 'Coursera',
    instructor: 'Alex Cowan',
    institution: 'University of Virginia',
    category: 'CoreCS',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/specializations/agile-development',
    description: 'Agile development, product/project practices and team delivery. Master Scrum, Kanban, user stories, sprint planning, and continuous release cadences.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 40,
    rating: 4.7,
    skillsTaught: ['Scrum & Kanban Methodologies', 'User Story Mapping', 'Sprint Planning & Retrospectives', 'Continuous Delivery Mindset'],
    tags: ['Final', 'Agile', 'Scrum', 'Project Management', 'University of Virginia'],
    isPublished: true,
  },
  {
    title: 'Generative AI with Large Language Models',
    provider: 'Coursera',
    instructor: 'DeepLearning.AI + AWS Instructors',
    institution: 'DeepLearning.AI',
    category: 'AI_ML',
    difficulty: 'Advanced',
    url: 'https://www.coursera.org/learn/generative-ai-with-llms',
    description: 'Modern GenAI/LLM concepts, model lifecycle and application-oriented understanding. Learn transformer fine-tuning (PEFT/LoRA), RLHF, and RAG architectures.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 16,
    rating: 4.8,
    skillsTaught: ['Generative AI & LLMs', 'Parameter-Efficient Fine-Tuning (PEFT/LoRA)', 'RLHF Alignment', 'Retrieval Augmented Generation (RAG)', 'LLM Deployment'],
    tags: ['Final', 'GenAI', 'LLMs', 'DeepLearning.AI', 'AWS', 'Transformers'],
    isPublished: true,
  },
  {
    title: 'Google IT Support Professional Certificate',
    provider: 'Coursera',
    instructor: 'Google Career Certificates',
    institution: 'Google',
    category: 'CoreCS',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/professional-certificates/google-it-support',
    description: 'Broader IT troubleshooting/networking/system support foundation; useful as an optional support-level credential covering hardware, OS, networking, and system admin.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 150,
    rating: 4.8,
    skillsTaught: ['Computer Hardware Troubleshooting', 'System Administration', 'Network Troubleshooting', 'Customer Support Workflows'],
    tags: ['Final', 'IT Support', 'Google', 'Troubleshooting', 'System Admin'],
    isPublished: true,
  },
];

module.exports = coursesSeedData;
