const coursesSeedData = [
  {
    title: 'Deep Learning Specialization',
    provider: 'Coursera',
    instructor: 'Andrew Ng',
    institution: 'DeepLearning.AI',
    category: 'AI_ML',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/specializations/deep-learning',
    description: 'Master neural networks, backpropagation, CNNs for computer vision, RNNs/Transformers for NLP, and hyperparameter tuning.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 80,
    rating: 4.9,
    skillsTaught: ['Deep Learning', 'PyTorch / TensorFlow', 'Neural Networks', 'Convolutional Networks'],
    tags: ['AI', 'Deep Learning', 'Andrew Ng', 'Coursera', 'Certifications'],
  },
  {
    title: 'Algorithms Specialization',
    provider: 'Coursera',
    instructor: 'Tim Roughgarden',
    institution: 'Stanford University',
    category: 'Algorithms',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/specializations/algorithms',
    description: 'Divide and conquer, randomized algorithms, graph search, shortest paths, greedy algorithms, and dynamic programming.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 64,
    rating: 4.8,
    skillsTaught: ['Asymptotic Analysis', 'Divide and Conquer', 'Graph Algorithms', 'Dynamic Programming'],
    tags: ['Algorithms', 'Stanford', 'DSA', 'Coursera'],
  },
  {
    title: 'Meta Front-End Developer Professional Certificate',
    provider: 'Coursera',
    instructor: 'Meta Staff',
    institution: 'Meta',
    category: 'FullStack',
    difficulty: 'Beginner',
    url: 'https://www.coursera.org/professional-certificates/meta-front-end-developer',
    description: 'Learn HTML, CSS, JavaScript, React, UI/UX principles, and version control from Meta engineers.',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 70,
    rating: 4.7,
    skillsTaught: ['React', 'JavaScript', 'HTML5/CSS3', 'Version Control'],
    tags: ['Frontend', 'React', 'Meta', 'Web Development'],
  },
  {
    title: 'Google Cloud Engineering Professional Certificate',
    provider: 'Coursera',
    instructor: 'Google Cloud Training',
    institution: 'Google Cloud',
    category: 'Cloud_DevOps',
    difficulty: 'Intermediate',
    url: 'https://www.coursera.org/professional-certificates/google-cloud-engineering',
    description: 'Deploying applications, monitoring operations, managing enterprise solutions on Google Cloud Platform (GCP).',
    isFree: false,
    hasFinancialAid: true,
    estimatedHours: 60,
    rating: 4.8,
    skillsTaught: ['GCP', 'Kubernetes Engine', 'Cloud Storage', 'IAM & VPC'],
    tags: ['Cloud', 'DevOps', 'Google Cloud', 'GCP'],
  },
];

module.exports = coursesSeedData;
