const hackathonsSeedData = [
  {
    name: 'Smart India Hackathon (SIH)',
    organizer: 'Ministry of Education & AICTE, Govt. of India',
    description: 'World’s biggest open innovation model for students to iterate, develop, and solve real-world problems faced by central ministries and industry partners.',
    registrationUrl: 'https://www.sih.gov.in/',
    startDate: new Date('2026-10-15T09:00:00.000Z'),
    endDate: new Date('2026-10-17T18:00:00.000Z'),
    registrationDeadline: new Date('2026-09-30T23:59:59.000Z'),
    location: 'Pan-India Nodal Centers / Hybrid',
    mode: 'Hybrid',
    teamSize: '6 Members (Mandatory 1 female member)',
    eligibility: 'All undergraduate engineering students across accredited institutions.',
    prizeInformation: '₹1,00,000 per problem statement + Incubation support',
    technology: ['AI/ML', 'FullStack', 'Blockchain', 'IoT', 'Cloud', 'Cybersecurity'],
    problemThemes: ['Smart Automation', 'Healthcare', 'Agriculture', 'Clean Water & Energy', 'Disaster Management'],
    status: 'Upcoming',
  },
  {
    name: 'HackMIT',
    organizer: 'Massachusetts Institute of Technology (MIT)',
    description: 'Premier global student hackathon bringing over 1,000 undergraduate hackers together to build innovative hardware and software solutions.',
    registrationUrl: 'https://hackmit.org/',
    startDate: new Date('2026-11-01T10:00:00.000Z'),
    endDate: new Date('2026-11-03T16:00:00.000Z'),
    registrationDeadline: new Date('2026-10-10T23:59:59.000Z'),
    location: 'Cambridge, MA / Virtual Stream',
    mode: 'Hybrid',
    teamSize: '1-4 Members',
    eligibility: 'Global undergraduate students.',
    prizeInformation: '$25,000+ total prize pool across sponsor tracks',
    technology: ['Generative AI', 'Web3', 'Developer Tools', 'Assistive Technology'],
    status: 'Upcoming',
  },
  {
    name: 'ETHIndia',
    organizer: 'Devfolio & Ethereum Foundation',
    description: 'Asia’s largest Ethereum hackathon empowering developers to build decentralized applications, smart contracts, zero-knowledge proofs, and Web3 infrastructure.',
    registrationUrl: 'https://ethindia.co/',
    startDate: new Date('2026-12-04T12:00:00.000Z'),
    endDate: new Date('2026-12-06T18:00:00.000Z'),
    registrationDeadline: new Date('2026-11-15T23:59:59.000Z'),
    location: 'Bangalore, India',
    mode: 'Offline',
    teamSize: '2-4 Members',
    eligibility: 'Open to all developers and students passionate about Web3.',
    prizeInformation: '$100,000+ in bounties & grants',
    technology: ['Solidity', 'Rust', 'EVM', 'ZK-Rollups', 'IPFS'],
    status: 'Upcoming',
  },
];

module.exports = hackathonsSeedData;
