// ========================================================
// 60 REAL-WORLD INDUSTRY PROJECTS SEED DATA
// 5 Projects per Field across 12 Disciplines
// ========================================================

// We will construct the seed array directly
const projectsSeedData = [
  // 1. AI / MACHINE LEARNING
  {
    title: 'AI Resume Skill Analyzer',
    slug: 'ai-resume-skill-analyzer',
    category: 'AI / Machine Learning',
    difficulty: 'LOW',
    description: 'Analyze resumes and job descriptions to extract key technical skills, identify competency gaps, and generate customized study plans.',
    problemStatement: 'Students and job seekers struggle to know if their resume matches ATS algorithms and target job descriptions.',
    targetUsers: 'Job applicants, campus placement cells, recruiters.',
    technologyStack: {
      frontend: ['React', 'TypeScript', 'TailwindCSS'],
      backend: ['Python', 'FastAPI', 'spaCy / Transformers'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'MVP with clean UI, resume PDF text extraction, cosine skill similarity, and gap analysis.',
      coreMilestones: ['PDF Text Extraction', 'spaCy NER Skill Extraction', 'FastAPI Match Endpoint', 'React Dashboard'],
    },
    status: 'Published',
  },
  {
    title: 'Smart Customer Support Ticket Classifier',
    slug: 'smart-customer-support-ticket-classifier',
    category: 'AI / Machine Learning',
    difficulty: 'MEDIUM',
    description: 'Automatically classify support tickets by department and urgency using PyTorch/scikit-learn with human-in-the-loop validation.',
    problemStatement: 'Enterprise support desks receive thousands of unstructured customer complaints daily causing routing bottlenecks.',
    targetUsers: 'Customer service teams, helpdesks, enterprise IT support.',
    technologyStack: {
      frontend: ['React', 'TypeScript'],
      backend: ['Python', 'FastAPI', 'scikit-learn', 'PyTorch'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'Nginx'],
    },
    mvp: {
      scope: 'Production-style API, role-based ticket review queue, confidence score thresholds, and automated routing.',
      coreMilestones: ['Model Training Pipeline', 'FastAPI Prediction Service', 'Triage Review Dashboard'],
    },
    status: 'Published',
  },
  {
    title: 'Predictive Maintenance Dashboard',
    slug: 'predictive-maintenance-dashboard',
    category: 'AI / Machine Learning',
    difficulty: 'MEDIUM',
    description: 'Predict machine component failure risk from sensor time-series data using Random Forest/XGBoost models and trigger preventative alerts.',
    problemStatement: 'Unplanned industrial machine downtime causes massive financial losses that could be prevented with sensor anomaly forecasting.',
    targetUsers: 'Plant engineers, industrial technicians, IoT operators.',
    technologyStack: {
      frontend: ['React', 'Recharts'],
      backend: ['Python', 'FastAPI', 'pandas', 'XGBoost'],
      database: ['PostgreSQL', 'TimescaleDB'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Sensor telemetry ingestion, time-series feature calculation, threshold risk scoring API, and alerting dashboard.',
      coreMilestones: ['Feature Engineering Pipeline', 'XGBoost Training', 'Real-time Alerting API'],
    },
    status: 'Published',
  },
  {
    title: 'Fraud Detection & Risk Scoring Platform',
    slug: 'fraud-detection-risk-scoring-platform',
    category: 'AI / Machine Learning',
    difficulty: 'HIGH',
    description: 'Real-time financial transaction scoring pipeline with SHAP model explainability, imbalanced learning, and compliance audit queues.',
    problemStatement: 'Financial institutions must evaluate millions of transaction events per second to block fraudulent card operations within milliseconds.',
    targetUsers: 'FinTech risk teams, compliance officers, banking fraud analysts.',
    technologyStack: {
      frontend: ['React', 'TypeScript'],
      backend: ['Python', 'FastAPI', 'PyTorch / XGBoost', 'Apache Kafka'],
      database: ['PostgreSQL', 'Redis'],
      devops: ['Docker', 'Prometheus', 'Grafana'],
    },
    mvp: {
      scope: 'Sub-50ms inference API, Kafka event ingestion, Redis feature store, and SHAP explainability dashboard.',
      coreMilestones: ['SMOTE Imbalanced Training', 'Kafka Stream Ingestion', 'SHAP Waterfall Plots', 'Alert Webhook'],
    },
    status: 'Published',
  },
  {
    title: 'Enterprise AI Decision Intelligence Platform',
    slug: 'enterprise-ai-decision-intelligence-platform',
    category: 'AI / Machine Learning',
    difficulty: 'HIGH',
    description: 'Comprehensive decision platform integrating multi-model revenue forecasting, anomaly detection, document intelligence, and executive AI summaries.',
    problemStatement: 'C-suite executives need unified analytics combining structured financial data with unstructured quarterly PDF reports.',
    targetUsers: 'Executive leaders, corporate strategists, data science leads.',
    technologyStack: {
      frontend: ['Next.js', 'React', 'TailwindCSS'],
      backend: ['Python', 'FastAPI', 'PyTorch', 'LangChain', 'pgvector'],
      database: ['PostgreSQL', 'Redis'],
      devops: ['Docker', 'Kubernetes', 'Helm'],
    },
    mvp: {
      scope: 'Microservice architecture, time-series forecasting, vector semantic search, and audit trail dashboard.',
      coreMilestones: ['Hybrid RAG + Forecasting', 'pgvector Semantic Indexing', 'Multi-tenant Kubernetes Cluster'],
    },
    status: 'Published',
  },

  // 2. GENERATIVE AI / LLM
  {
    title: 'College Document Q&A Assistant',
    slug: 'college-document-qa-assistant',
    category: 'Generative AI / LLM',
    difficulty: 'LOW',
    description: 'Ask questions over college circulars, notices, and PDF handbooks with verifiable citations using ChromaDB vector search.',
    problemStatement: 'Students miss critical deadlines because notices are buried inside hundreds of administrative PDF circulars.',
    targetUsers: 'University students, faculty, admissions staff.',
    technologyStack: {
      frontend: ['React', 'TypeScript'],
      backend: ['Python', 'FastAPI', 'LangChain', 'ChromaDB'],
      database: ['SQLite / PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Document upload interface, PDF chunking, ChromaDB embedding retrieval, and cited streaming responses.',
      coreMilestones: ['PDF Ingestion Pipeline', 'ChromaDB Vector Store', 'Streaming Chat UI'],
    },
    status: 'Published',
  },
  {
    title: 'Company Knowledge Copilot',
    slug: 'company-knowledge-copilot',
    category: 'Generative AI / LLM',
    difficulty: 'MEDIUM',
    description: 'Search internal technical documentation and HR policies with role-based document access and RAG evaluation benchmarks.',
    problemStatement: 'Engineers waste hours finding internal API specs and company policies across fragmented wikis.',
    targetUsers: 'Software engineers, HR managers, internal employees.',
    technologyStack: {
      frontend: ['Next.js', 'React'],
      backend: ['Python', 'FastAPI', 'pgvector', 'LlamaIndex'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'GitHub Actions'],
    },
    mvp: {
      scope: 'RBAC document filter, pgvector hybrid search, RAGAS retrieval evaluation, and Dockerized deployment.',
      coreMilestones: ['RBAC Vector Filtering', 'Hybrid BM25 + Vector Search', 'RAGAS Evaluation'],
    },
    status: 'Published',
  },
  {
    title: 'AI Meeting Action Manager',
    slug: 'ai-meeting-action-manager',
    category: 'Generative AI / LLM',
    difficulty: 'MEDIUM',
    description: 'Convert meeting audio recordings into concise summaries, key decisions, assignees, and tracked deadlines with Whisper STT.',
    problemStatement: 'Hours spent in meetings result in forgotten action items and lost accountability without structured summaries.',
    targetUsers: 'Project managers, remote development teams, consultants.',
    technologyStack: {
      frontend: ['React', 'TypeScript'],
      backend: ['Python', 'FastAPI', 'OpenAI Whisper', 'Pydantic'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Audio transcription, structured JSON decision extraction, task assignment board, and email export.',
      coreMilestones: ['Whisper Audio Processing', 'Structured Extraction Schema', 'Action Item Dashboard'],
    },
    status: 'Published',
  },
  {
    title: 'AI Customer Support Agent with Human Handoff',
    slug: 'ai-customer-support-agent-human-handoff',
    category: 'Generative AI / LLM',
    difficulty: 'HIGH',
    description: 'Autonomous customer support agent executing database tool calls with safety guardrails and real-time live human agent escalation.',
    problemStatement: 'Chatbots hallucinate or frustrate customers when encountering complex edge cases without human intervention.',
    targetUsers: 'E-commerce support teams, SaaS companies, customer ops.',
    technologyStack: {
      frontend: ['React', 'WebSockets'],
      backend: ['Python', 'LangGraph', 'FastAPI', 'Redis'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'Nginx'],
    },
    mvp: {
      scope: 'Tool calling for order tracking, confidence scoring, NeMo safety guardrails, and WebSocket agent handoff queue.',
      coreMilestones: ['LangGraph State Machine', 'Tool Calling Handlers', 'Live Agent WebSocket Queue'],
    },
    status: 'Published',
  },
  {
    title: 'Enterprise Multi-Agent Operations Assistant',
    slug: 'enterprise-multi-agent-operations-assistant',
    category: 'Generative AI / LLM',
    difficulty: 'HIGH',
    description: 'Autonomous multi-agent system coordinating database analytics, Jira ticketing, and documentation with permission controls.',
    problemStatement: 'Complex business operations require multiple specialized roles to collaborate, research, and execute tasks.',
    targetUsers: 'DevOps engineers, IT operations, corporate analysts.',
    technologyStack: {
      frontend: ['Next.js', 'React'],
      backend: ['Python', 'AutoGen / LangGraph', 'FastAPI', 'RabbitMQ'],
      database: ['PostgreSQL', 'Redis'],
      devops: ['Docker', 'Kubernetes'],
    },
    mvp: {
      scope: 'Multi-agent orchestration, state machines, permission boundaries, LangSmith observability, and audit logs.',
      coreMilestones: ['Agent Orchestration Network', 'RabbitMQ Async Queue', 'Permission Enforcement Layer'],
    },
    status: 'Published',
  },

  // 3. CYBERSECURITY
  {
    title: 'Password Security & Phishing Awareness Portal',
    slug: 'password-security-phishing-awareness-portal',
    category: 'Cybersecurity',
    difficulty: 'LOW',
    description: 'Interactive security awareness platform with simulated educational phishing campaigns and password entropy scorecards.',
    problemStatement: 'Human error is the leading cause of security breaches; employees need hands-on simulation training.',
    targetUsers: 'Students, enterprise staff, security awareness trainers.',
    technologyStack: {
      frontend: ['React', 'CSS'],
      backend: ['Node.js', 'Express.js', 'Argon2'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Password entropy calculator, simulated phishing landing page, user security scorecards, and learning modules.',
      coreMilestones: ['Entropy Scoring Algorithm', 'Phishing Simulation Engine', 'Admin Analytics Dashboard'],
    },
    status: 'Published',
  },
  {
    title: 'Web Vulnerability Scanner for Authorized Labs',
    slug: 'web-vulnerability-scanner-authorized-labs',
    category: 'Cybersecurity',
    difficulty: 'MEDIUM',
    description: 'Automated vulnerability scanner checking HTTP security headers, outdated SSL, SQLi injection points, and XSS indicators in authorized labs.',
    problemStatement: 'Developers accidentally leave open security misconfigurations and OWASP vulnerabilities in newly deployed web apps.',
    targetUsers: 'Security analysts, QA engineers, junior penetration testers.',
    technologyStack: {
      frontend: ['React', 'TypeScript'],
      backend: ['Python', 'FastAPI', 'requests', 'BeautifulSoup'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Target crawler, automated OWASP checklist tests, PDF report generation, and remediation guidance.',
      coreMilestones: ['URL Crawler Engine', 'Vulnerability Test Suite', 'Report Generator'],
    },
    status: 'Published',
  },
  {
    title: 'Security Log Analyzer / Mini SIEM',
    slug: 'security-log-analyzer-mini-siem',
    category: 'Cybersecurity',
    difficulty: 'MEDIUM',
    description: 'Centralized log collector and analyzer parsing Linux auth logs, firewall logs, and web traffic to detect brute-force and SQLi attacks.',
    problemStatement: 'Security operations teams are overwhelmed by disconnected log files and lack unified threat detection rules.',
    targetUsers: 'SOC analysts, system administrators, incident responders.',
    technologyStack: {
      frontend: ['React', 'Recharts'],
      backend: ['Python', 'FastAPI', 'OpenSearch / Elasticsearch'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'Filebeat'],
    },
    mvp: {
      scope: 'Log ingestion API, Sigma rule parser, brute-force alert trigger, and real-time threat map dashboard.',
      coreMilestones: ['Syslog Ingestion Pipeline', 'Sigma Rule Engine', 'Real-time Alert Dashboard'],
    },
    status: 'Published',
  },
  {
    title: 'Endpoint Threat Detection Dashboard',
    slug: 'endpoint-threat-detection-dashboard',
    category: 'Cybersecurity',
    difficulty: 'HIGH',
    description: 'Endpoint monitoring telemetry pipeline mapping Linux process trees and network connections to the MITRE ATT&CK matrix.',
    problemStatement: 'Stealthy malware executes in memory and establishes persistence without triggering basic antivirus signatures.',
    targetUsers: 'SOC Tier-2 analysts, threat hunters, security engineers.',
    technologyStack: {
      frontend: ['React', 'TypeScript'],
      backend: ['Python', 'eBPF / osquery', 'FastAPI', 'OpenSearch'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'Nginx'],
    },
    mvp: {
      scope: 'osquery telemetry agent, MITRE ATT&CK taxonomy mapping, process tree visualizer, and alert triage queue.',
      coreMilestones: ['Telemetry Collector', 'MITRE ATT&CK Mapper', 'Process Tree Canvas View'],
    },
    status: 'Published',
  },
  {
    title: 'Cloud Security Posture Management Platform',
    slug: 'cloud-security-posture-management-platform',
    category: 'Cybersecurity',
    difficulty: 'HIGH',
    description: 'Automated CIS benchmark security auditor scanning AWS/GCP cloud resources for exposed buckets, loose IAM policies, and unencrypted volumes.',
    problemStatement: 'Cloud misconfigurations are the primary attack vector for cloud data breaches.',
    targetUsers: 'Cloud security engineers, DevSecOps teams, compliance auditors.',
    technologyStack: {
      frontend: ['Next.js', 'React'],
      backend: ['Go / Python', 'AWS Boto3', 'Open Policy Agent (OPA)', 'FastAPI'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'Terraform'],
    },
    mvp: {
      scope: 'Cloud SDK resource crawler, OPA policy evaluation engine, compliance scorecard, and auto-remediation triggers.',
      coreMilestones: ['AWS Resource Ingestion', 'OPA Rego Policy Engine', 'Remediation Workflow'],
    },
    status: 'Published',
  },

  // 4. WEB DEVELOPMENT / FRONTEND
  {
    title: 'Accessible College Event Portal',
    slug: 'accessible-college-event-portal',
    category: 'Web Development',
    difficulty: 'LOW',
    description: 'WCAG 2.1 AA-compliant campus event ticketing platform with keyboard accessibility, high contrast themes, and screen reader optimizations.',
    problemStatement: 'Campus portals are often inaccessible to students with visual or motor impairments.',
    targetUsers: 'University students, event organizers, accessibility compliance officers.',
    technologyStack: {
      frontend: ['React', 'Next.js', 'TypeScript', 'TailwindCSS'],
      backend: ['REST API'],
      database: ['PostgreSQL / Mock API'],
      devops: ['Vercel'],
    },
    mvp: {
      scope: 'Event calendar, ARIA-accessible booking modal, ticket QR generator, and organizer portal.',
      coreMilestones: ['WCAG Accessibility Audit', 'Keyboard Navigation', 'Event Booking Flow'],
    },
    status: 'Published',
  },
  {
    title: 'Personal Finance Dashboard',
    slug: 'personal-finance-dashboard',
    category: 'Web Development',
    difficulty: 'LOW',
    description: 'Interactive personal budgeting application with Zustand state management, customizable financial widgets, and interactive Recharts data visualizations.',
    problemStatement: 'Students struggle to manage living expenses and track monthly budget allocations without complex spreadsheets.',
    targetUsers: 'Students, young professionals, personal budgeters.',
    technologyStack: {
      frontend: ['React', 'TypeScript', 'Zustand', 'Recharts'],
      backend: ['LocalStorage / Node.js Mock API'],
      database: ['IndexedDB'],
      devops: ['GitHub Pages'],
    },
    mvp: {
      scope: 'Category breakdown charts, recurring subscription tracking, monthly savings goals, and CSV transaction export.',
      coreMilestones: ['Zustand State Architecture', 'Recharts Graphs', 'IndexedDB Offline Persistence'],
    },
    status: 'Published',
  },
  {
    title: 'Multi-Vendor Service Marketplace Frontend',
    slug: 'multi-vendor-service-marketplace-frontend',
    category: 'Web Development',
    difficulty: 'MEDIUM',
    description: 'Faceted search marketplace frontend with instant filtering, multi-step booking wizards, customer reviews, and provider availability calendars.',
    problemStatement: 'Service marketplaces suffer from sluggish client-side filtering and complex multi-step appointment scheduling.',
    targetUsers: 'Service consumers, freelance technicians, marketplace operators.',
    technologyStack: {
      frontend: ['Next.js App Router', 'TypeScript', 'TanStack Query', 'TailwindCSS'],
      backend: ['REST API'],
      database: ['PostgreSQL'],
      devops: ['Vercel', 'Docker'],
    },
    mvp: {
      scope: 'Faceted URL-driven search filters, multi-step appointment booking wizard, provider review forms, and responsive mobile layout.',
      coreMilestones: ['Faceted URL Filter Engine', 'TanStack Query Caching', 'Booking Wizard UI'],
    },
    status: 'Published',
  },
  {
    title: 'Real-Time Collaboration Board',
    slug: 'real-time-collaboration-board',
    category: 'Web Development',
    difficulty: 'MEDIUM',
    description: 'Trello-inspired project board with drag-and-drop column organization, live user cursor presence, and instant WebSocket synchronization.',
    problemStatement: 'Remote teams require low-latency collaborative project boards with live updates and conflict-free editing.',
    targetUsers: 'Agile development teams, students working on group projects.',
    technologyStack: {
      frontend: ['React', 'TypeScript', 'dnd-kit', 'Socket.io Client'],
      backend: ['Node.js', 'Express', 'Socket.io'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Drag-and-drop cards, WebSocket room broadcasting, live user avatars, and optimistic UI mutations.',
      coreMilestones: ['dnd-kit Kanban Board', 'Socket.io Multi-User Sync', 'Optimistic Updates'],
    },
    status: 'Published',
  },
  {
    title: 'Enterprise Workflow SaaS Frontend',
    slug: 'enterprise-workflow-saas-frontend',
    category: 'Web Development',
    difficulty: 'HIGH',
    description: 'Large-scale enterprise dashboard with dynamic drag-and-drop workflow builder, permission matrices, Core Web Vitals optimization, and Playwright E2E testing.',
    problemStatement: 'Enterprise SaaS interfaces become slow and unmaintainable without strict component design systems and testing.',
    targetUsers: 'Operations managers, enterprise administrators, compliance officers.',
    technologyStack: {
      frontend: ['Next.js', 'TypeScript', 'React Flow', 'Playwright', 'Vitest'],
      backend: ['GraphQL / REST APIs'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'GitHub Actions'],
    },
    mvp: {
      scope: 'Visual node-based workflow builder (React Flow), custom component design system, dark mode token system, and Playwright tests.',
      coreMilestones: ['Design System Implementation', 'React Flow Visual Canvas', 'Playwright Test Suite'],
    },
    status: 'Published',
  },

  // 5. FULL-STACK DEVELOPMENT
  {
    title: 'Student Management System',
    slug: 'student-management-system',
    category: 'Full Stack',
    difficulty: 'LOW',
    description: 'Complete student information system with student records, course enrollment, attendance tracking, and admin grade cards.',
    problemStatement: 'Educational institutions need simple, reliable portals to manage student records without proprietary enterprise bloat.',
    targetUsers: 'Academic administrators, students, faculty.',
    technologyStack: {
      frontend: ['React', 'TailwindCSS'],
      backend: ['Node.js', 'Express.js', 'JWT Auth'],
      database: ['PostgreSQL / MongoDB'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'CRUD on students and courses, JWT auth with role permissions, attendance logging, and CSV export.',
      coreMilestones: ['JWT Auth Middleware', 'Student CRUD API', 'Admin Analytics View'],
    },
    status: 'Published',
  },
  {
    title: 'Hospital Appointment & Records Platform',
    slug: 'hospital-appointment-records-platform',
    category: 'Full Stack',
    difficulty: 'MEDIUM',
    description: 'Healthcare booking platform with doctor schedules, patient appointment booking with Redis locking, encrypted medical notes, and RBAC.',
    problemStatement: 'Double-booking of clinician consultation slots and insecure patient records plague clinic management systems.',
    targetUsers: 'Patients, doctors, clinic receptionists.',
    technologyStack: {
      frontend: ['Next.js', 'TypeScript', 'TailwindCSS'],
      backend: ['NestJS / Node.js', 'PostgreSQL', 'Redis'],
      database: ['PostgreSQL (ACID Transactions)'],
      devops: ['Docker', 'Nginx'],
    },
    mvp: {
      scope: 'Appointment booking with Redis slot reservation, doctor calendar management, encrypted medical records, and SMS alerts.',
      coreMilestones: ['Redis Slot Locking', 'PostgreSQL ACID Transactions', 'Doctor Calendar View'],
    },
    status: 'Published',
  },
  {
    title: 'B2B Inventory & Order Management SaaS',
    slug: 'b2b-inventory-order-management-saas',
    category: 'Full Stack',
    difficulty: 'MEDIUM',
    description: 'Multi-warehouse stock inventory tracking with purchase order approvals, sales invoices, low-stock webhook alerts, and audit logging.',
    problemStatement: 'Distributors lose revenue due to out-of-stock items and discrepancies between purchase orders and warehouse deliveries.',
    targetUsers: 'Warehouse managers, wholesale distributors, procurement teams.',
    technologyStack: {
      frontend: ['React', 'TypeScript', 'TailwindCSS'],
      backend: ['NestJS', 'PostgreSQL', 'Redis'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'GitHub Actions'],
    },
    mvp: {
      scope: 'Multi-warehouse inventory reconciliation, purchase order workflow, PDF invoice generator, and webhook triggers.',
      coreMilestones: ['Inventory Movement Ledger', 'PDF Invoice Generator', 'Low-Stock Webhook'],
    },
    status: 'Published',
  },
  {
    title: 'FinTech-Style Expense & Cashflow Platform',
    slug: 'fintech-expense-cashflow-platform',
    category: 'Full Stack',
    difficulty: 'HIGH',
    description: 'Corporate financial accounting platform with double-entry ledgers, expense receipt OCR scanning, and predictive cashflow forecast models.',
    problemStatement: 'Small businesses struggle to forecast future cashflow deficits and reconcile multi-currency invoice payments.',
    targetUsers: 'Finance controllers, small business owners, corporate accountants.',
    technologyStack: {
      frontend: ['Next.js', 'TypeScript', 'TailwindCSS'],
      backend: ['NestJS', 'Python ML microservice', 'PostgreSQL', 'Redis'],
      database: ['PostgreSQL (Double-Entry Schema)'],
      devops: ['Docker Compose', 'GitHub Actions'],
    },
    mvp: {
      scope: 'Double-entry ledger database schema, immutable transaction audit logs, Python forecasting microservice, and export reports.',
      coreMilestones: ['Double-Entry Ledger Engine', 'Python ML Forecasting API', 'Multi-tenant Audit Logs'],
    },
    status: 'Published',
  },
  {
    title: 'Multi-Tenant Business Operations SaaS',
    slug: 'multi-tenant-business-operations-saas',
    category: 'Full Stack',
    difficulty: 'HIGH',
    description: 'Complete multi-tenant SaaS application with tenant database isolation, Stripe subscription billing, BullMQ background jobs, and OpenTelemetry.',
    problemStatement: 'Building scalable B2B SaaS requires strict multi-tenant data isolation, recurring billing, and reliable background task workers.',
    targetUsers: 'Enterprise B2B clients, SaaS operators, developers.',
    technologyStack: {
      frontend: ['Next.js App Router', 'TypeScript', 'TailwindCSS'],
      backend: ['NestJS', 'BullMQ', 'PostgreSQL (Schema per tenant)', 'Redis'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'Kubernetes', 'OpenTelemetry'],
    },
    mvp: {
      scope: 'Schema-per-tenant isolation middleware, Stripe webhook subscription management, BullMQ async reports, and OpenTelemetry tracing.',
      coreMilestones: ['Tenant Isolation Middleware', 'Stripe Billing Webhooks', 'BullMQ Worker Pipeline'],
    },
    status: 'Published',
  },

  // 6. BACKEND / API ENGINEERING
  {
    title: 'Secure REST API Starter Platform',
    slug: 'secure-rest-api-starter-platform',
    category: 'Backend',
    difficulty: 'LOW',
    description: 'Production-ready REST API boilerplate with Zod input validation, JWT authentication, centralized error handling, and Swagger OpenAPI documentation.',
    problemStatement: 'Developers waste time rebuilding security, validation, and authentication boilerplate across every new backend project.',
    targetUsers: 'Backend developers, API teams, technical leads.',
    technologyStack: {
      frontend: ['Swagger UI'],
      backend: ['Node.js', 'Express.js / FastAPI', 'Zod', 'JWT'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'JWT authentication, RBAC middleware, Zod request body validation, centralized error responses, and Swagger documentation.',
      coreMilestones: ['Zod Validation Layer', 'JWT Auth Pipeline', 'Swagger Auto-Documentation'],
    },
    status: 'Published',
  },
  {
    title: 'Order Processing API with Idempotency',
    slug: 'order-processing-api-idempotency',
    category: 'Backend',
    difficulty: 'MEDIUM',
    description: 'High-throughput order placement backend with Idempotency-Key headers, database transaction isolation, Redis distributed caching, and BullMQ queues.',
    problemStatement: 'Duplicate network retries and payment double-charges occur when APIs lack strict idempotent request handling.',
    targetUsers: 'E-commerce engineering teams, payment platform developers.',
    technologyStack: {
      frontend: ['Admin Dashboard'],
      backend: ['NestJS / Spring Boot', 'Redis', 'BullMQ / RabbitMQ'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Idempotency-Key Redis filter, ACID inventory decrement transaction, asynchronous payment worker, and order status transitions.',
      coreMilestones: ['Idempotency Middleware', 'ACID Inventory Reservation', 'BullMQ Order Queue'],
    },
    status: 'Published',
  },
  {
    title: 'Central Notification Microservice',
    slug: 'central-notification-microservice',
    category: 'Backend',
    difficulty: 'MEDIUM',
    description: 'Centralized microservice to dispatch Email, SMS, and Push alerts with templating, exponential backoff retries, dead-letter queues, and rate limits.',
    problemStatement: 'Microservices independently managing email and SMS providers result in inconsistent templates and unhandled vendor outages.',
    targetUsers: 'Microservice platforms, backend engineering teams.',
    technologyStack: {
      frontend: ['Admin Dashboard'],
      backend: ['Node.js / TypeScript', 'RabbitMQ / Kafka', 'Redis'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'RabbitMQ message broker ingestion, token-bucket rate limiting, dead-letter queue retries, and delivery status webhooks.',
      coreMilestones: ['RabbitMQ Consumer Workers', 'Dead Letter Queue Retries', 'Template Engine'],
    },
    status: 'Published',
  },
  {
    title: 'Event-Driven E-Commerce Backend',
    slug: 'event-driven-ecommerce-backend',
    category: 'Backend',
    difficulty: 'HIGH',
    description: 'Decoupled microservice architecture using Apache Kafka event streams, the Outbox Pattern, and Saga orchestration for distributed order workflows.',
    problemStatement: 'Monolithic architectures struggle to scale order spikes and cause cascading failures when one subsystem goes offline.',
    targetUsers: 'Enterprise e-commerce platforms, high-scale retail backends.',
    technologyStack: {
      frontend: ['React Admin'],
      backend: ['Java / Spring Boot or Node.js/NestJS', 'Apache Kafka', 'Redis'],
      database: ['PostgreSQL'],
      devops: ['Docker Compose', 'Prometheus'],
    },
    mvp: {
      scope: 'Catalog, Order, Payment, and Inventory services communicating via Kafka topics, transactional outbox pattern, and Saga compensations.',
      coreMilestones: ['Transactional Outbox Pattern', 'Kafka Event Streaming', 'Saga Orchestration'],
    },
    status: 'Published',
  },
  {
    title: 'API Gateway & Service Mesh Platform',
    slug: 'api-gateway-service-mesh-platform',
    category: 'Backend',
    difficulty: 'HIGH',
    description: 'High-performance API Gateway written in Go/Node.js with JWT verification, token-bucket rate limiting, circuit breaker pattern, and Prometheus telemetry.',
    problemStatement: 'Microservices need centralized traffic routing, SSL termination, authentication, rate limiting, and failure containment.',
    targetUsers: 'Platform engineering teams, infrastructure architects.',
    technologyStack: {
      frontend: ['Grafana Telemetry'],
      backend: ['Go / Node.js', 'Redis', 'Resilience4j / Gobreaker'],
      database: ['Redis Key-Value'],
      devops: ['Docker', 'Kubernetes', 'Prometheus', 'Grafana'],
    },
    mvp: {
      scope: 'Reverse proxy routing, Redis token-bucket rate limiter, circuit breaker with fallback responses, and Prometheus exporter.',
      coreMilestones: ['Reverse Proxy Router in Go', 'Redis Rate Limiter', 'Circuit Breaker Pattern'],
    },
    status: 'Published',
  },

  // 7. DATA SCIENCE / ANALYTICS
  {
    title: 'Student Performance Analytics',
    slug: 'student-performance-analytics',
    category: 'Data Science',
    difficulty: 'LOW',
    description: 'Exploratory data analysis project identifying academic risk factors from attendance, internal test marks, and study hours using Streamlit.',
    problemStatement: 'Faculty lack early visual indicators to identify students at risk of failing before semester exams.',
    targetUsers: 'Academic advisors, department heads, faculty mentors.',
    technologyStack: {
      frontend: ['Streamlit'],
      backend: ['Python', 'pandas', 'NumPy', 'Seaborn'],
      database: ['SQLite / PostgreSQL'],
      devops: ['Streamlit Cloud'],
    },
    mvp: {
      scope: 'Dataset cleaning, correlation heatmaps, student grade distribution plots, and interactive Streamlit filter dashboard.',
      coreMilestones: ['Data Cleaning Pipeline', 'EDA Visualization', 'Streamlit Dashboard'],
    },
    status: 'Published',
  },
  {
    title: 'Retail Sales & Customer Analytics',
    slug: 'retail-sales-customer-analytics',
    category: 'Data Science',
    difficulty: 'LOW',
    description: 'Retail sales analysis system calculating RFM customer segments, store performance metrics, and product category trends with Plotly charts.',
    problemStatement: 'Retail business owners need actionable customer retention metrics beyond simple revenue totals.',
    targetUsers: 'Retail store owners, marketing managers, data analysts.',
    technologyStack: {
      frontend: ['Plotly / Dash'],
      backend: ['Python', 'pandas', 'SQL (PostgreSQL)'],
      database: ['PostgreSQL (Window Functions)'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Complex SQL window queries, RFM customer segmentation score matrix, and interactive revenue dashboards.',
      coreMilestones: ['SQL Window Aggregations', 'RFM Segmentation Algorithm', 'Plotly Dashboard'],
    },
    status: 'Published',
  },
  {
    title: 'Business KPI Intelligence Dashboard',
    slug: 'business-kpi-intelligence-dashboard',
    category: 'Data Science',
    difficulty: 'MEDIUM',
    description: 'Automated data pipeline consolidating CRM, sales, and marketing data into an executive KPI dashboard calculating CAC, LTV, and churn rates.',
    problemStatement: 'Leadership teams waste days manually compiling monthly operational KPI reports from disparate data silos.',
    targetUsers: 'Executives, growth leads, financial analysts.',
    technologyStack: {
      frontend: ['React', 'Power BI / Recharts'],
      backend: ['Python', 'FastAPI', 'pandas', 'PostgreSQL'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Automated daily data ingestion, KPI metric calculation formulas (LTV, CAC, MRR), and executive dashboard.',
      coreMilestones: ['ETL Transformation Script', 'FastAPI Metric Endpoint', 'Executive KPI UI'],
    },
    status: 'Published',
  },
  {
    title: 'Demand Forecasting & Inventory Optimization',
    slug: 'demand-forecasting-inventory-optimization',
    category: 'Data Science',
    difficulty: 'MEDIUM',
    description: 'Time-series forecasting model using Facebook Prophet and ARIMA to predict product demand across regional warehouses and calculate safety stock.',
    problemStatement: 'Overstocking leads to tied-up capital while stockouts cause lost revenue during seasonal demand surges.',
    targetUsers: 'Supply chain managers, inventory planners, logistics teams.',
    technologyStack: {
      frontend: ['React', 'Recharts'],
      backend: ['Python', 'Prophet', 'statsmodels', 'FastAPI'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Time-series trend & seasonality decomposition, multi-step Prophet forecasting, safety stock recommendations, and prediction API.',
      coreMilestones: ['Prophet Time Series Model', 'Safety Stock Formula', 'Prediction REST API'],
    },
    status: 'Published',
  },
  {
    title: 'Enterprise Data Warehouse & Analytics Platform',
    slug: 'enterprise-data-warehouse-analytics-platform',
    category: 'Data Science',
    difficulty: 'HIGH',
    description: 'End-to-end data platform with Apache Airflow DAG scheduling, dbt dimensional data transformation (star schema), and Superset BI dashboards.',
    problemStatement: 'Enterprise business intelligence is crippled by messy raw data and lack of automated data quality pipelines.',
    targetUsers: 'Data engineers, BI developers, corporate data teams.',
    technologyStack: {
      frontend: ['Apache Superset'],
      backend: ['Python', 'Apache Airflow', 'dbt', 'PostgreSQL / Snowflake'],
      database: ['PostgreSQL (Dimensional Star Schema)'],
      devops: ['Docker Compose'],
    },
    mvp: {
      scope: 'Airflow DAG orchestration, dbt automated data testing & lineage, dimensional star-schema data marts, and Superset charts.',
      coreMilestones: ['Airflow DAG Ingestion', 'dbt Star Schema Models', 'Superset BI Dashboards'],
    },
    status: 'Published',
  },

  // 8. CLOUD / DEVOPS / SRE
  {
    title: 'Dockerized Full-Stack Web Deployment',
    slug: 'dockerized-fullstack-web-deployment',
    category: 'Cloud / DevOps',
    difficulty: 'LOW',
    description: 'Containerize frontend, backend API, and PostgreSQL database with multi-stage Dockerfiles, Docker Compose networking, and environment isolation.',
    problemStatement: '"It works on my machine" bugs occur when development environments differ from production deployments.',
    targetUsers: 'Junior developers, full-stack engineers, DevOps beginners.',
    technologyStack: {
      frontend: ['React (Nginx container)'],
      backend: ['Node.js Express container'],
      database: ['PostgreSQL container with volume persistence'],
      devops: ['Docker', 'Docker Compose', 'GitHub Actions'],
    },
    mvp: {
      scope: 'Multi-stage Dockerfile builds, Docker Compose service orchestration, persistent volume mounts, and GitHub Actions CI build check.',
      coreMilestones: ['Multi-Stage Dockerfiles', 'Docker Compose Orchestration', 'CI Build Workflow'],
    },
    status: 'Published',
  },
  {
    title: 'Automated CI/CD Pipeline with Zero-Downtime',
    slug: 'automated-cicd-pipeline-zero-downtime',
    category: 'Cloud / DevOps',
    difficulty: 'MEDIUM',
    description: 'Production CI/CD workflow with automated linting, test suites, Trivy vulnerability scanning, Docker registry publishing, and rolling zero-downtime deploy.',
    problemStatement: 'Manual deployment causes outages, skipped security checks, and high mean-time-to-recovery (MTTR).',
    targetUsers: 'DevOps engineers, release managers, full-stack teams.',
    technologyStack: {
      frontend: ['React App'],
      backend: ['Node.js / Python'],
      database: ['PostgreSQL on AWS RDS / VM'],
      devops: ['GitHub Actions', 'Docker Hub', 'Trivy', 'Nginx Reverse Proxy', 'AWS EC2'],
    },
    mvp: {
      scope: 'GitHub Actions workflow, Trivy security gate, zero-downtime Nginx reload script, and automated rollback triggers.',
      coreMilestones: ['GitHub Actions CI Pipeline', 'Trivy Vulnerability Scan', 'Zero-Downtime CD Script'],
    },
    status: 'Published',
  },
  {
    title: 'Cloud Observability & Monitoring Dashboard',
    slug: 'cloud-observability-monitoring-dashboard',
    category: 'Cloud / DevOps',
    difficulty: 'MEDIUM',
    description: 'Comprehensive observability stack collecting Prometheus application metrics and system stats, visualized on custom Grafana dashboards with alert webhooks.',
    problemStatement: 'Engineers discover server crashes and API memory leaks only after users complain on social media.',
    targetUsers: 'Site Reliability Engineers (SREs), backend architects, cloud teams.',
    technologyStack: {
      frontend: ['Grafana Dashboards'],
      backend: ['Node.js / Python Prometheus client'],
      database: ['Prometheus TSDB'],
      devops: ['Prometheus', 'Grafana', 'Alertmanager', 'Docker'],
    },
    mvp: {
      scope: 'Prometheus metric endpoint instrumentation (RED metrics), Grafana dashboard visualization, and Slack/Discord alert triggers.',
      coreMilestones: ['Prometheus Metric Exporter', 'Grafana Custom Dashboard', 'Alertmanager Webhook'],
    },
    status: 'Published',
  },
  {
    title: 'Kubernetes Microservice Cluster Platform',
    slug: 'kubernetes-microservice-cluster-platform',
    category: 'Cloud / DevOps',
    difficulty: 'HIGH',
    description: 'Deploy resilient microservices on Kubernetes with Ingress controllers, Horizontal Pod Autoscaling (HPA), ConfigMaps, Secrets, and rolling updates.',
    problemStatement: 'High-traffic applications crash when individual containers cannot dynamically scale under load spikes.',
    targetUsers: 'Cloud engineers, infrastructure architects, enterprise DevOps.',
    technologyStack: {
      frontend: ['Nginx Ingress Controller'],
      backend: ['Microservice Pods (Go / Node.js)'],
      database: ['StatefulSet PostgreSQL'],
      devops: ['Kubernetes (k8s)', 'Helm Charts', 'HPA', 'AWS EKS / Minikube'],
    },
    mvp: {
      scope: 'Helm chart packaging, Ingress routing, CPU-based Horizontal Pod Autoscaling, liveness/readiness health probes, and cluster metrics.',
      coreMilestones: ['Helm Chart Packaging', 'HPA Auto-scaling Test', 'Ingress Routing Setup'],
    },
    status: 'Published',
  },
  {
    title: 'Internal Developer Platform (IDP) with IaC',
    slug: 'internal-developer-platform-idp-iac',
    category: 'Cloud / DevOps',
    difficulty: 'HIGH',
    description: 'Self-service developer portal allowing engineering teams to spin up cloud infrastructure, CI/CD pipelines, and microservice boilerplates with Terraform.',
    problemStatement: 'Developers wait weeks for DevOps teams to manually provision cloud resources and deployment pipelines.',
    targetUsers: 'Platform engineering teams, enterprise software developers.',
    technologyStack: {
      frontend: ['React / Backstage'],
      backend: ['Node.js / Go', 'Terraform CLI', 'GitHub Actions'],
      database: ['PostgreSQL'],
      devops: ['Terraform (IaC)', 'Kubernetes', 'AWS / GCP'],
    },
    mvp: {
      scope: 'Terraform cloud modules (VPC, EKS, RDS), self-service service creation UI, automated CI/CD pipeline generator, and policy guardrails.',
      coreMilestones: ['Terraform Cloud Modules', 'Self-Service React Portal', 'Automated Golden Path CI/CD'],
    },
    status: 'Published',
  },

  // 9. MOBILE / CROSS-PLATFORM
  {
    title: 'Campus Companion Mobile App',
    slug: 'campus-companion-mobile-app',
    category: 'Mobile',
    difficulty: 'LOW',
    description: 'Cross-platform mobile application providing daily college timetables, offline campus maps, department notices, and assignment notifications.',
    problemStatement: 'College students struggle with disorganized schedule announcements and finding campus facilities.',
    targetUsers: 'University students, professors, campus visitors.',
    technologyStack: {
      frontend: ['Flutter / Dart or React Native'],
      backend: ['Firebase Auth', 'Cloud Firestore'],
      database: ['Firestore / SQLite'],
      devops: ['Firebase Hosting', 'Play Console'],
    },
    mvp: {
      scope: 'Timetable schedule with notifications, interactive department map, notice board, and offline caching.',
      coreMilestones: ['Flutter UI Architecture', 'Firestore Real-time Sync', 'Push Notifications'],
    },
    status: 'Published',
  },
  {
    title: 'Medicine Reminder & Health Tracker App',
    slug: 'medicine-reminder-health-tracker-app',
    category: 'Mobile',
    difficulty: 'MEDIUM',
    description: 'Mobile medication adherence app with local alarm scheduling, dosage tracking, SQLite offline persistence, and doctor appointment sync.',
    problemStatement: 'Patients frequently forget medication dosages leading to health complications and failed treatments.',
    targetUsers: 'Patients, caregivers, elderly users (educational/demo use).',
    technologyStack: {
      frontend: ['Flutter / React Native'],
      backend: ['Node.js / FastAPI'],
      database: ['SQLite (Local)', 'PostgreSQL (Cloud Sync)'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Exact background alarms, SQLite offline database, medication schedule manager, and REST cloud backup sync.',
      coreMilestones: ['Background Alarm Service', 'SQLite Offline DB', 'Cloud Sync API'],
    },
    status: 'Published',
  },
  {
    title: 'Field Sales & Route Management App',
    slug: 'field-sales-route-management-app',
    category: 'Mobile',
    difficulty: 'MEDIUM',
    description: 'Offline-first mobile application for field sales representatives to log client orders, manage visit itineraries, and sync data upon reconnection.',
    problemStatement: 'Field agents working in poor connectivity zones lose order data and face delayed communication with central warehouses.',
    targetUsers: 'Sales representatives, field technicians, retail distributors.',
    technologyStack: {
      frontend: ['Flutter / React Native', 'WatermelonDB / SQLite'],
      backend: ['Node.js', 'PostgreSQL', 'Google Maps SDK'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Offline database with delta sync on reconnection, GPS location check-in, photo invoice uploads, and customer visit logs.',
      coreMilestones: ['Offline-First Sync Engine', 'GPS Route Logging', 'Order Entry UI'],
    },
    status: 'Published',
  },
  {
    title: 'Last-Mile Delivery Driver & Customer Suite',
    slug: 'last-mile-delivery-driver-customer-suite',
    category: 'Mobile',
    difficulty: 'HIGH',
    description: 'Dual mobile application ecosystem for customers and delivery drivers featuring live GPS route tracking, status updates, and digital signature proof.',
    problemStatement: 'Customers demand live real-time package delivery tracking and dispatchers need driver location telemetry.',
    targetUsers: 'Delivery drivers, e-commerce customers, dispatch managers.',
    technologyStack: {
      frontend: ['Flutter (Customer App + Driver App)'],
      backend: ['NestJS', 'Redis Geospatial', 'WebSockets'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'Nginx'],
    },
    mvp: {
      scope: 'Live WebSocket geospatial tracking, background location broadcasting, digital signature capture, and customer status push alerts.',
      coreMilestones: ['Redis Geo Driver Tracking', 'WebSocket Live Map Stream', 'Digital Signature Pad'],
    },
    status: 'Published',
  },
  {
    title: 'IoT Fleet Telemetry & Remote Control App',
    slug: 'iot-fleet-telemetry-remote-control-app',
    category: 'Mobile',
    difficulty: 'HIGH',
    description: 'Industrial mobile application displaying live sensor telemetry from connected hardware via MQTT over WebSockets with remote reboot controls.',
    problemStatement: 'Field engineers lack instant mobile visibility and control over remote edge hardware installations.',
    targetUsers: 'Field service engineers, industrial plant managers, IoT operators.',
    technologyStack: {
      frontend: ['Flutter', 'MQTT Client'],
      backend: ['Node.js / Python', 'MQTT Broker (EMQX)', 'TimescaleDB'],
      database: ['TimescaleDB'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'MQTT WebSocket telemetry ingestion, real-time sensor graphs, threshold push notifications, and cryptographic remote commands.',
      coreMilestones: ['MQTT WebSocket Integration', 'Live Time-Series Graphs', 'Remote Command Payload'],
    },
    status: 'Published',
  },

  // 10. IOT / EDGE / EMBEDDED
  {
    title: 'Smart Energy & Power Monitor',
    slug: 'smart-energy-power-monitor',
    category: 'IoT / Edge',
    difficulty: 'LOW',
    description: 'Read real-time voltage and current sensor readings using ESP32, publish data over MQTT, and render daily energy consumption trends on a React dashboard.',
    problemStatement: 'Homeowners and lab managers lack visibility into appliance-level electricity consumption and energy waste.',
    targetUsers: 'Homeowners, facility managers, sustainability engineers.',
    technologyStack: {
      frontend: ['React', 'Chart.js'],
      backend: ['ESP32 (C/C++)', 'MQTT Protocol', 'Node.js Express'],
      database: ['PostgreSQL / SQLite'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'ESP32 sensor sampling (ADC), MQTT publisher, Node.js listener, and web dashboard displaying kilowatt-hour metrics.',
      coreMilestones: ['ESP32 Firmware ADC Reading', 'MQTT Communication Pipeline', 'React Energy Dashboard'],
    },
    status: 'Published',
  },
  {
    title: 'Smart Plant Irrigation & Soil Monitor',
    slug: 'smart-plant-irrigation-soil-monitor',
    category: 'IoT / Edge',
    difficulty: 'LOW',
    description: 'Measure soil moisture, temperature, and ambient light with ESP32; trigger relay water pumps automatically and send Telegram bot alerts.',
    problemStatement: 'Agricultural greenhouses and domestic plants die from erratic watering schedules and lack of moisture monitoring.',
    targetUsers: 'Greenhouse farmers, urban gardeners, botanical labs.',
    technologyStack: {
      frontend: ['Telegram Bot UI'],
      backend: ['ESP32 (C++)', 'Capacitive Sensors', 'Python Telegram Bot'],
      database: ['Flash Storage / EEPROM'],
      devops: ['PlatformIO'],
    },
    mvp: {
      scope: 'Soil moisture threshold logic, relay pump actuator activation, ESP32 deep sleep mode, and Telegram alert messages.',
      coreMilestones: ['Capacitive Sensor Calibration', 'Relay Actuation Code', 'Telegram Bot Alerts'],
    },
    status: 'Published',
  },
  {
    title: 'Cold-Chain Pharmaceutical Temperature Monitor',
    slug: 'cold-chain-pharmaceutical-temperature-monitor',
    category: 'IoT / Edge',
    difficulty: 'MEDIUM',
    description: 'Track temperature and humidity in pharmaceutical storage boxes with local SD card offline logging, MQTT telemetry, and compliance alerts.',
    problemStatement: 'Vaccines and biological pharmaceuticals spoil when temperature excursions during transport go unrecorded.',
    targetUsers: 'Pharmaceutical logistics, hospital pharmacies, vaccine couriers.',
    technologyStack: {
      frontend: ['React Dashboard'],
      backend: ['ESP32 (C++)', 'DHT22 / DS18B20', 'MQTT', 'Node.js'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Calibrated temperature reading, offline SD card logging buffer, MQTT upload, and excursion warning dashboard.',
      coreMilestones: ['Sensor Firmware with SD Card Logging', 'MQTT Excursion Alerts', 'Compliance History View'],
    },
    status: 'Published',
  },
  {
    title: 'Industrial Machine Health & Vibration Analyzer',
    slug: 'industrial-machine-health-vibration-analyzer',
    category: 'IoT / Edge',
    difficulty: 'MEDIUM',
    description: 'Compute Fast Fourier Transform (FFT) features from accelerometer vibration data on edge Raspberry Pi devices to detect motor mechanical imbalance.',
    problemStatement: 'Industrial motor mechanical failures cause sudden catastrophic shutdowns that are preceded by subtle high-frequency vibration changes.',
    targetUsers: 'Industrial maintenance teams, plant reliability engineers.',
    technologyStack: {
      frontend: ['React', 'Plotly'],
      backend: ['Raspberry Pi (Python)', 'scikit-learn Anomaly Detection', 'MQTT'],
      database: ['TimescaleDB'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Edge accelerometer sampling, FFT frequency spectrum computation, Isolation Forest anomaly scoring, and time-series dashboard.',
      coreMilestones: ['Edge FFT Signal Processing', 'Isolation Forest ML Model', 'TimescaleDB Vibration Visualizer'],
    },
    status: 'Published',
  },
  {
    title: 'Smart Factory Digital Twin & Telemetry Platform',
    slug: 'smart-factory-digital-twin-telemetry-platform',
    category: 'IoT / Edge',
    difficulty: 'HIGH',
    description: 'Interactive 3D digital twin of an assembly line rendering live sensor telemetry streams using Three.js/WebGL with predictive bottleneck warnings.',
    problemStatement: 'Plant operators struggle to conceptualize spatial telemetry and machine bottleneck points across sprawling factory floors.',
    targetUsers: 'Manufacturing directors, process engineers, smart factory operators.',
    technologyStack: {
      frontend: ['React Three Fiber (Three.js 3D)', 'WebSockets'],
      backend: ['Node.js / Python', 'MQTT Broker', 'TimescaleDB'],
      database: ['TimescaleDB'],
      devops: ['Docker', 'Nginx'],
    },
    mvp: {
      scope: '3D factory layout in WebGL, real-time machine telemetry binding, color-coded heatmaps, and simulated throughput testing.',
      coreMilestones: ['Three.js 3D Assembly Scene', 'WebSocket Telemetry Stream', 'Predictive Bottleneck Alerting'],
    },
    status: 'Published',
  },

  // 11. BLOCKCHAIN / WEB3
  {
    title: 'Academic Certificate Verification DApp',
    slug: 'academic-certificate-verification-dapp',
    category: 'Blockchain / Web3',
    difficulty: 'LOW',
    description: 'Issue and verify tamper-proof university graduation certificates on an EVM blockchain testnet to permanently eliminate credential forgery.',
    problemStatement: 'Fake academic credentials are widespread and manual university verification processes take weeks.',
    targetUsers: 'Universities, employers, students, credential evaluators.',
    technologyStack: {
      frontend: ['React', 'TypeScript', 'ethers.js / wagmi'],
      backend: ['Solidity Smart Contracts', 'Hardhat'],
      database: ['Ethereum Sepolia Testnet'],
      devops: ['Hardhat', 'IPFS'],
    },
    mvp: {
      scope: 'Solidity certificate registry contract, Metamask issuer portal, public verification search bar, and SHA-256 PDF validation.',
      coreMilestones: ['Solidity Certificate Contract', 'Metamask Signing Flow', 'Public Verification UI'],
    },
    status: 'Published',
  },
  {
    title: 'Transparent Charity Donation Ledger',
    slug: 'transparent-charity-donation-ledger',
    category: 'Blockchain / Web3',
    difficulty: 'LOW',
    description: 'Record public charity donation transactions and project milestone releases on an immutable smart contract ledger.',
    problemStatement: 'Donors lack transparency into whether charitable donations actually reach intended humanitarian projects.',
    targetUsers: 'Non-profit organizations, donors, NGO auditors.',
    technologyStack: {
      frontend: ['React', 'TypeScript', 'ethers.js'],
      backend: ['Solidity', 'Hardhat'],
      database: ['EVM Testnet'],
      devops: ['Vercel'],
    },
    mvp: {
      scope: 'Payable donation smart contract, milestone fund release voting, transaction event indexing, and donor transparency dashboard.',
      coreMilestones: ['Payable Contract Functions', 'Event Indexing UI', 'Milestone Release Flow'],
    },
    status: 'Published',
  },
  {
    title: 'Supply Chain Provenance & Traceability Demo',
    slug: 'supply-chain-provenance-traceability-demo',
    category: 'Blockchain / Web3',
    difficulty: 'MEDIUM',
    description: 'Track physical product ownership transfer from manufacturer to distributor to retailer with cryptographic signature proofs and IPFS metadata.',
    problemStatement: 'Counterfeit pharmaceutical and luxury goods infiltrate supply chains without verifiable chain-of-custody provenance.',
    targetUsers: 'Supply chain auditors, manufacturers, retail consumers.',
    technologyStack: {
      frontend: ['Next.js', 'React', 'TailwindCSS'],
      backend: ['Solidity', 'Node.js', 'IPFS (Pinata)'],
      database: ['EVM Testnet', 'PostgreSQL (Off-chain cache)'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Product lifecycle smart contract, IPFS metadata pinning, QR code verification scanner, and participant role transitions.',
      coreMilestones: ['Solidity State Machine Contract', 'IPFS Metadata Pinning', 'QR Code Verification Scanner'],
    },
    status: 'Published',
  },
  {
    title: 'Token-Gated Community & Resource Platform',
    slug: 'token-gated-community-resource-platform',
    category: 'Blockchain / Web3',
    difficulty: 'MEDIUM',
    description: 'Grant exclusive access to engineering research papers and courses based on cryptographic verification of user NFT / token holdings using SIWE.',
    problemStatement: 'Creators and academic communities need decentralized access gating without relying on proprietary platform accounts.',
    targetUsers: 'Engineering communities, digital creators, research DAOs.',
    technologyStack: {
      frontend: ['Next.js', 'wagmi', 'ethers.js'],
      backend: ['Node.js / Express', 'Sign-In With Ethereum (SIWE)'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'SIWE cryptographic wallet login, ERC-721 token balance verification middleware, protected resource viewer, and course library.',
      coreMilestones: ['SIWE Authentication Pipeline', 'Token Balance Verification Middleware', 'Gated Resource Vault'],
    },
    status: 'Published',
  },
  {
    title: 'Enterprise Asset Provenance & Verifiable Claims',
    slug: 'enterprise-asset-provenance-verifiable-claims',
    category: 'Blockchain / Web3',
    difficulty: 'HIGH',
    description: 'Combine enterprise off-chain PostgreSQL database transactions with cryptographic Merkle tree root anchors on-chain for privacy-preserving auditing.',
    problemStatement: 'Enterprises need the tamper-proof guarantees of blockchain without exposing confidential customer transaction data publicly.',
    targetUsers: 'Enterprise auditors, banking consortia, compliance officers.',
    technologyStack: {
      frontend: ['React', 'TypeScript'],
      backend: ['NestJS', 'Solidity', 'Merkle Tree (OpenZeppelin)'],
      database: ['PostgreSQL', 'EVM Testnet'],
      devops: ['Docker', 'GitHub Actions'],
    },
    mvp: {
      scope: 'Merkle tree root batch generation, smart contract root anchoring, cryptographic Merkle proof verification endpoint, and audit dashboard.',
      coreMilestones: ['Merkle Tree Generation Script', 'On-Chain Root Anchor Contract', 'Cryptographic Proof Verifier UI'],
    },
    status: 'Published',
  },

  // 12. SOFTWARE ENGINEERING / SYSTEM DESIGN
  {
    title: 'Project Management API & Team Dashboard',
    slug: 'project-management-api-team-dashboard',
    category: 'Software Engineering / System Design',
    difficulty: 'LOW',
    description: 'Sprint planning and task tracking platform with Layered Clean Architecture, Jest automated test suites, and team velocity metrics.',
    problemStatement: 'Engineering teams need clean, modular project management APIs without convoluted micro-management bloat.',
    targetUsers: 'Software development teams, Agile scrum masters, engineering students.',
    technologyStack: {
      frontend: ['React', 'TailwindCSS'],
      backend: ['NestJS / Node.js', 'Jest', 'TypeScript'],
      database: ['PostgreSQL'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Clean Controller-Service-Repository architecture, task sprint management, unit test coverage >80%, and velocity charts.',
      coreMilestones: ['Layered Architecture Setup', 'Jest Test Coverage Suite', 'Sprint Velocity UI'],
    },
    status: 'Published',
  },
  {
    title: 'High-Throughput Scalable URL Shortener',
    slug: 'high-throughput-scalable-url-shortener',
    category: 'Software Engineering / System Design',
    difficulty: 'MEDIUM',
    description: 'System design benchmark URL shortening platform featuring Base62 distributed key encoding, Redis Cache-Aside pattern, and sub-5ms redirects.',
    problemStatement: 'High-volume URL shortening services must handle billions of read redirections while maintaining unique compact hash codes.',
    targetUsers: 'Marketing platforms, social media apps, system design interview prep.',
    technologyStack: {
      frontend: ['React', 'TypeScript'],
      backend: ['Go / Node.js', 'Redis', 'Base62'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'Nginx'],
    },
    mvp: {
      scope: 'Base62 key generator, Redis Cache-Aside lookup, sliding-window rate limiting, and click analytics tracking.',
      coreMilestones: ['Base62 Encoding Engine', 'Redis Cache-Aside Layer', 'Click Analytics Pipeline'],
    },
    status: 'Published',
  },
  {
    title: 'Concurrent Online Examination Platform',
    slug: 'concurrent-online-examination-platform',
    category: 'Software Engineering / System Design',
    difficulty: 'MEDIUM',
    description: 'High-concurrency exam engine handling simultaneous test submissions with pessimistic database locks, auto-save drafts, and anti-cheat tab alerts.',
    problemStatement: 'Online exam servers crash during simultaneous submission deadlines and suffer from test submission loss.',
    targetUsers: 'Universities, online certification bodies, recruitment test platforms.',
    technologyStack: {
      frontend: ['React', 'TypeScript'],
      backend: ['Spring Boot / NestJS', 'Redis', 'WebSockets'],
      database: ['PostgreSQL (Pessimistic Locking)'],
      devops: ['Docker'],
    },
    mvp: {
      scope: 'Auto-save draft sync, timer-enforced submission with pessimistic DB locks, WebSocket proctor alerts, and automated score calculation.',
      coreMilestones: ['Pessimistic Locking Submission API', 'WebSocket Anti-Cheat Proctor', 'Automated Grading Engine'],
    },
    status: 'Published',
  },
  {
    title: 'Ride / Delivery Dispatch & Geospatial Matcher',
    slug: 'ride-delivery-dispatch-geospatial-matcher',
    category: 'Software Engineering / System Design',
    difficulty: 'HIGH',
    description: 'Real-time geospatial dispatch engine matching customer ride/delivery requests to optimal nearby drivers using Redis GEO and PostGIS spatial indexing.',
    problemStatement: 'Matching millions of moving drivers and riders in real-time requires sub-second geospatial index computation without race conditions.',
    targetUsers: 'Ride-sharing companies, courier services, system design interview candidates.',
    technologyStack: {
      frontend: ['React', 'Mapbox / Leaflet', 'WebSockets'],
      backend: ['Go / Java / Node.js', 'Redis (GEO commands)', 'PostGIS'],
      database: ['PostgreSQL (PostGIS Extension)'],
      devops: ['Docker', 'Nginx'],
    },
    mvp: {
      scope: 'Redis GEO spatial indexing, Hungarian matching algorithm for optimal driver assignment, WebSocket live updates, and surge price calculator.',
      coreMilestones: ['Redis GEO Dispatch Algorithm', 'PostGIS Route Optimization', 'Live Mapbox Visualizer'],
    },
    status: 'Published',
  },
  {
    title: 'Distributed Job Scheduling & Worker Platform',
    slug: 'distributed-job-scheduling-worker-platform',
    category: 'Software Engineering / System Design',
    difficulty: 'HIGH',
    description: 'Fault-tolerant distributed background task scheduler featuring Redlock distributed locks, leader election, Kafka message queues, and Prometheus health metrics.',
    problemStatement: 'Cron jobs in distributed clusters suffer from duplicate execution, worker node crashes, and lack of retry visibility.',
    targetUsers: 'Platform engineering teams, backend architects, enterprise systems.',
    technologyStack: {
      frontend: ['React Dashboard'],
      backend: ['Go / Java', 'Kafka / RabbitMQ', 'Redis (Redlock)'],
      database: ['PostgreSQL'],
      devops: ['Docker', 'Kubernetes', 'Prometheus'],
    },
    mvp: {
      scope: 'Distributed Redlock coordination, leader election, idempotent worker task execution, exponential failure retry queue, and Prometheus metrics.',
      coreMilestones: ['Redlock Distributed Lock Engine', 'Kafka Worker Pool', 'Prometheus Metric Exporter'],
    },
    status: 'Published',
  },
];

module.exports = projectsSeedData;
