const youtubeResourcesSeedData = [
  {
    title: 'Striver’s A2Z DSA Course / Sheet',
    channelName: 'take U forward (Striver)',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLgUwDviBIf0oF6QL8m22w1hIDC1vJ_BHz',
    videoUrl: 'https://www.youtube.com/@takeUforward',
    category: 'DSA',
    difficulty: 'Complete Series',
    description: 'Comprehensive, step-by-step topic breakdown of Data Structures & Algorithms from absolute basics to advanced DP and Graphs.',
    topicsCovered: ['Arrays', 'Recursion', 'Binary Search', 'Trees', 'Graphs', 'Dynamic Programming', 'Trie'],
    estimatedHours: 120,
    tags: ['DSA', 'Striver', 'takeUforward', 'Coding Interview', 'SDE Sheet'],
  },
  {
    title: 'Algorithms Complete Playlist',
    channelName: 'Abdul Bari',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLDN4rrl48XKpZkf03iYFl-O29szjTrs_O',
    category: 'DSA',
    difficulty: 'Intermediate',
    description: 'Deep visual explanations of Divide & Conquer, Greedy Algorithms, Dynamic Programming, and Backtracking.',
    topicsCovered: ['Asymptotic Analysis', 'Divide and Conquer', 'Greedy Method', 'Dynamic Programming', 'NP-Completeness'],
    estimatedHours: 45,
    tags: ['Algorithms', 'Abdul Bari', 'Visual Learning', 'Academic Foundation'],
  },
  {
    title: 'Operating Systems & Concurrency Deep Dive',
    channelName: 'Gate Smashers (Varun Singla)',
    playlistUrl: 'https://www.youtube.com/playlist?list=PLxCzCOWd7aiGz9donHRrE9I3Mwn6XdP8p',
    category: 'OS',
    difficulty: 'Beginner',
    description: 'Crisp, structured semester and placement preparation lectures for CPU Scheduling, Process Sync, Deadlocks, and Paging.',
    topicsCovered: ['Process Control Block', 'Semaphores', 'Deadlock Detection', 'Paging & TLB', 'Disk Scheduling'],
    estimatedHours: 35,
    tags: ['Operating Systems', 'Gate Smashers', 'Semester Prep', 'Placement'],
  },
  {
    title: 'Computer Networks Full Course',
    channelName: 'Kunal Kushwaha / NetworkChuck',
    playlistUrl: 'https://www.youtube.com/playlist?list=PL9gnSGHSqcnq9Q2i_pX-qX3y_v3NrqrC_',
    category: 'Networks',
    difficulty: 'Beginner',
    description: 'Hands-on networking lectures covering IP addressing, Subnetting, TCP 3-way handshake, DNS, Wireshark, and Routing protocols.',
    topicsCovered: ['OSI Model', 'Subnetting', 'TCP / UDP', 'DNS / HTTP', 'Packet Tracing'],
    estimatedHours: 25,
    tags: ['Computer Networks', 'Subnetting', 'TCP/IP', 'Wireshark'],
  },
  {
    title: 'Full Stack Web Development / MERN Course',
    channelName: 'Traversy Media / Dave Gray',
    videoUrl: 'https://www.youtube.com/c/TraversyMedia',
    category: 'WebDev',
    difficulty: 'Beginner',
    description: 'Modern full-stack application development with Node.js, Express, React, and MongoDB.',
    topicsCovered: ['REST APIs', 'React Hooks', 'JWT Authentication', 'MongoDB Atlas'],
    estimatedHours: 40,
    tags: ['FullStack', 'MERN', 'React', 'Node.js'],
  },
];

module.exports = youtubeResourcesSeedData;
